### ISSUE TITLE
CFPの掲載＠日本語・英語:  tomoko takahashiさんによる「テストです」

### ISSUE THREAD

**Issue by tomoco95** [scalamatsuri/2020.scalamatsuri.org#1]
```
id: "" # proposalは人名-No
ja:
  candidate:
    name: "tomoko takahashi"
    twitter: scalamatsuri
    github: tomoco95
    icon: https://twitter.com/scalamatsuri
    organization: JSA
    contributes:
      - - てすと1
- てすと2
- てすと3
    speaker_experience:
      - - テスト1
- テスト2
- テスト3
  program:
    title: "テストです"
    length: 40分
    language: Japanese
    tags:
      - Tools, Scalaビギナー（Scala歴1年くらいまで）, Virtual coin / Blockchain
    suggestions:
      - test1
test2
test3
    detail: |
      てすとてすと
en:
  candidate:
    name: TOMOKO TAKAHASHI
    twitter: scalamatsuri
    github: tomoco95
    icon: https://twitter.com/scalamatsuri
    organization: JSA
    contributes:
      - - てすと1
- てすと2
- てすと3
    speaker_experience:
      - - テスト1
- テスト2
- テスト3
  program:
    title: "test"
    length: 40分
    language: Japanese
    tags:
      - Tools, Scalaビギナー（Scala歴1年くらいまで）, Virtual coin / Blockchain
    suggestions:
      - test1
test2
test3
    detail: |
      testtest
```

- [ ] 日本語版の掲載
- [ ] 英語版の掲載
