### ISSUE TITLE
追加発表者の掲載: 「てすと」

### ISSUE THREAD

**Issue by tomoco95** [scalamatsuri/2020.scalamatsuri.org#10]
```
  candidate:
    name: "岩堀 知子"
    twitter: https://twitter.com/scalamatsuri
    github: tomoco95
    icon: https://twitter.com/scalamatsuri
    organization: JSA
    contributes:
      - - oss1
- oss2
- oss3
    speaker_experience:
      - - test1
- test2
- test3
  program:
    title: "てすと"
```

- 英語の情報
```
- name: iwahori tomoko
```

- [ ] 追加発表者の掲載
