### ISSUE TITLE
[英語フォーム] CFPの掲載: Afsal Thajさんによる「zio-config - Unveiling the much simplified advanced functional programming in Scala」

### ISSUE THREAD

**Issue by tomoco95** [scalamatsuri/2020.scalamatsuri.org#106]
```
id: "" # proposalは人名-No
en:
  candidate:
    name: Afsal Thaj
    twitter: https://twitter.com/afsalt2
    github: https://github.com/afsalthaj
    other_sns: 
    icon: https://avatars2.githubusercontent.com/u/7448613?s=460&v=4
    organization: Principal Consultant, Simple Machines
    contributes:
      - zio-configv(author, maintainer)
safe-string-interpolation (author, maintainer)
other contributions.
    speaker_experience:
      - Scalasyd, Australia
Beescala, Slovenia
Functional Scala, London (talk accepted)
  program:
    title: "zio-config - Unveiling the much simplified advanced functional programming in Scala"
    length: 40 minutes
    language: English
    tags:
      - Functional Programming, Tools, Best Practices
    keywords:
      - Free Applicative
Program introspection
Zero dependency
    detail: |
      I will talk about my library zio-config (https://github.com/zio/zio-config)- that aims to have  a purely functional, yet a thin interface to access configuration information inside an application. The purpose of the talk is not only to demonstrate what zio-config is, but to demonstrate the fact that sticking on to fundamentals and finding the right structure enables writing purely functional libraries with zero complexity. zio-config is built on solid foundations of FP leveraging program introspection - that gels with Free Applicative style encoding, while staying insanely simple for anyone.
```

- [ ] 英語版の掲載

- 追加発表者の有無
```

```
- [ ] Yesの場合には追加発表者を掲載する
