### ISSUE TITLE
[英語フォーム] CFPの掲載: Justin Heyes-Jonesさんによる「Pure Functional Programming for Beginners」

### ISSUE THREAD

**Issue by tomoco95** [scalamatsuri/2020.scalamatsuri.org#108]
```
id: "" # proposalは人名-No
en:
  candidate:
    name: Justin Heyes-Jones
    twitter: @justinhj
    github: https://github.com/justinhj
    other_sns: https://www.linkedin.com/in/justinheyesjones/
    icon: https://twitter.com/justinhj/photo
    organization: Yoppworks
    contributes:
      - Contributed to ZIO, Cats, Fetch, Tapir. Ammonite
Developer, Maintainer of 
https://github.com/justinhj/fp-starter-pack.g8
https://github.com/justinhj/astar-algorithm-cpp
https://github.com/justinhj/hnfetchjs

    speaker_experience:
      - Scale by the Bay 2019: Gentle Introduction to Comonads https://youtu.be/kVnJtiN1dbk
Vancouver Scala Meetup 2019: FUNCTORS TO COMONADS IN 30 MINUTES
 https://justinhj.github.io/comonad-reveal/
Vancouver Functional Programming 2018: From IO to ZIO 

  program:
    title: "Pure Functional Programming for Beginners"
    length: 40 minutes
    language: English
    tags:
      - Functional Programming, Scala Beginners (~1year), Software Design and Architecture
    keywords:
      - monoids
pure functional programming
    detail: |
      What is pure functional programming? How can you use it to make your Scala programs easier to test, easier to reason about and more reusable?
```

- [ ] 英語版の掲載

- 追加発表者の有無
```

```
- [ ] Yesの場合には追加発表者を掲載する
