### ISSUE TITLE
追加発表者の掲載: 「」

### ISSUE THREAD

**Issue by tomoco95** [scalamatsuri/2020.scalamatsuri.org#12]
```
  candidate:
    name: ""
    twitter: 
    github: 
    icon: 
    organization: 
    contributes:
      - 
    speaker_experience:
      - 
  program:
    title: ""
```

- 英語の情報
```
- name: 
```

- [ ] 追加発表者の掲載
