### ISSUE TITLE
[英語フォーム] CFPの和訳と掲載: Krzysztof Ciesielski さんによる「Reactive Manifesto 6 years later」

### ISSUE THREAD

**Issue by tomoco95** [scalamatsuri/2020.scalamatsuri.org#126]
```
id: "" # proposalは人名-No
ja:
  candidate:
    name: "Krzysztof Ciesielski"
    twitter: https://twitter.com/kpciesielski
    github: https://github.com/kciesielski
    other_sns: 
    icon: https://pbs.twimg.com/profile_images/1151236555304054785/JJEQYIq__400x400.png
    organization: SoftwareMill
    contributes:
      - Alpakka Kafka https://github.com/akka/alpakka-kafka
scala-clippy https://github.com/softwaremill/scala-clippy
sbt-softwaremill https://github.com/softwaremill/sbt-softwaremill
    speaker_experience:
      - Reactive Summit 2016, 
Scala Matsuri 2017 https://www.youtube.com/watch?v=Ux83mZcEKTU&list=PL39pyF64-WFKe1KiOdAqurBfJo5upj3FJ&index=19,
LambdAle 2018 https://www.youtube.com/watch?v=nSGSA2xAf2U
  program:
    title: ""
    length: 40 minutes
    language: English
    tags:
      - Best Practices, Software Design and Architecture, Microservices
    keywords:
      - reactive
architecture
design
    detail: |
      
```

- 英語の情報
```
- title: Reactive Manifesto 6 years later
- detail: It’s been a while since the Reactive Manifesto got widely announced and discussed. What changed since then? Was it a meaningful movement that shaped the direction of the evolution of software engineering? Or just another fancy set of buzzwords? This talk summarizes what “reactive” really means today and how the technological landscape looks like within the Scala ecosystem after it got stirred 6 years ago.
```

- [ ] 和訳
- [ ] 日本語版の掲載

- 追加発表者の有無
```

```
  - [ ] Yesの場合には追加発表者を掲載する
