### ISSUE TITLE
[英語フォーム] CFPの和訳と掲載: Hungai Kevin Amuhinda さんによる「Help, my Akka Cluster is broken!」

### ISSUE THREAD

**Issue by tomoco95** [scalamatsuri/2020.scalamatsuri.org#141]
```
id: "" # proposalは人名-No
ja:
  candidate:
    name: "Hungai Kevin Amuhinda"
    twitter: https://twitter.com/Hungai
    github: https://github.com/hungaikev
    other_sns: 
    icon: https://github.com/hungaikev.png
    organization: 
    contributes:
      - 
    speaker_experience:
      - https://www.youtube.com/watch?v=lTJ0L92C-9k&t=1s  https://www.youtube.com/watch?v=HSgb7gOO1Ig&t=1s
  program:
    title: ""
    length: 40 minutes
    language: English
    tags:
      - Tools, Best Practices, DevOps, Microservices
    keywords:
      - DevOps, Akka Cluster, Monitoring
    detail: |
      
```

- 英語の情報
```
- title: Help, my Akka Cluster is broken!
- detail: While Akka Cluster is designed to be fault-tolerant, there will be times when your environment just isn't working as expected. This session will discuss our experiences of how to most effectively collect and understand Akka Cluster diagnostics. We'll talk through using these diagnostics to work out what's gone wrong, and how to recover from a system outage. Using this new-found knowledge, you will be equipped to handle any problem your cluster throws at you.
```

- [ ] 和訳
- [ ] 日本語版の掲載

- 追加発表者の有無
```

```
  - [ ] Yesの場合には追加発表者を掲載する
