### ISSUE TITLE
[英語フォーム] CFPの掲載: Loic DIVADさんによる「Streaming Apps and Poison Pills: Handle the Unexpected with Kafka Streams」

### ISSUE THREAD

**Issue by tomoco95** [scalamatsuri/2020.scalamatsuri.org#150]
```
id: "" # proposalは人名-No
en:
  candidate:
    name: Loic DIVAD
    twitter: https://twitter.com/LoicMDivad
    github: https://github.com/DivLoic
    other_sns: https://www.linkedin.com/in/lo%C3%AFc-divad-3a5a9893/
    icon: https://avatars0.githubusercontent.com/u/7292538?s=460&v=4
    organization: Publicis Sapient Engineering
    contributes:
      - 
    speaker_experience:
      - This presentation has been played at Kafka Summit San Francisco 2019: https://www.confluent.io/kafka-summit-san-francisco-2019/streaming-apps-and-poison-pills-handle-the-unexpected-with-kafka-streams.

I'm also have 3 years of experience as technical speaker: https://speakerdeck.com/loicdivad
  program:
    title: "Streaming Apps and Poison Pills: Handle the Unexpected with Kafka Streams"
    length: 40 minutes
    language: English
    tags:
      - Big Data / Fast Data, Best Practices
    keywords:
      - Kafka
EventStreams
LiveCoding
    detail: |
      This Scala Live coding demonstrates how to deal with corrupted messages in a stream of events processed with Kafka Streams. Apache Kafka’s Streams API lets us process messages from different topics with very low latency. Messages may have different formats, schemas and may even be serialised in different ways. What happens when an undesirable message comes in the flow? When an error occurs, real-time applications can’t always wait for manual recovery and need to handle such failures. The presentation includes valuable experiences from building and running Kafka Streams projects in production.
```

- [ ] 英語版の掲載

- 追加発表者の有無
```

```
- [ ] Yesの場合には追加発表者を掲載する
