### ISSUE TITLE
[日本語フォーム] CFPの掲載:  リチャード 伊真岡さんによる「Scala 3のマーケット・ポジショニング」

### ISSUE THREAD

**Issue by tomoco95** [scalamatsuri/2020.scalamatsuri.org#155]
```
id: "" # proposalは人名-No
ja:
  candidate:
    name: "リチャード 伊真岡"
    twitter: https://twitter.com/RichardImaokaJP
    github: https://github.com/richardimaoka
    other_sns: 
    icon: https://s.gravatar.com/avatar/14bfbc98a7d5ed3574be08f6b176ce70?s=80
    organization: マーベリック株式会社 技術広報
    contributes:
      - 
    speaker_experience:
     - Scala 関西 Summit 2019 https://speakerdeck.com/richardimaokajp/javafei-tong-qi-chu-li
builderscon 2018 https://builderscon.io/tokyo/2018/session/3b06e658-0386-4603-be45-798f77361b86
Fun Fun Functional (2) 関数型言語Lightning Talks!! https://speakerdeck.com/richardimaokajp/scala-ziowobatutichu-li-nishi-tutemita
  program:
    title: "Scala 3のマーケット・ポジショニング"
    length: 40分
    language: Japanese
    tags:
      - Others
    keywords:
      - Scala 3
hiring
business
    detail: |
      Scalaは過去のマーケティング戦略を間違ったのでしょうか？いくつかの後発言語はScalaより多くの開発者を獲得しました。一方Scalaは開発者採用が難しく、キラーフィーチャーのない言語になったのでしょうか？この発表は技術的側面に加え、他言語の拡大戦略やビジネストレンドを分析し、Scala 3が現状を変えるのか、私達開発者に何を与えるのか、私達がScalaや技術の発展にどう貢献できるか検討します。
en:
  candidate:
    name: Richard Imaoka
    twitter: https://twitter.com/RichardImaokaJP
    github: https://github.com/richardimaoka
    other_sns: 
    icon: https://s.gravatar.com/avatar/14bfbc98a7d5ed3574be08f6b176ce70?s=80
    organization: マーベリック株式会社 技術広報
    contributes:
      - 
    speaker_experience:
      - Scala 関西 Summit 2019 https://speakerdeck.com/richardimaokajp/javafei-tong-qi-chu-li
builderscon 2018 https://builderscon.io/tokyo/2018/session/3b06e658-0386-4603-be45-798f77361b86
Fun Fun Functional (2) 関数型言語Lightning Talks!! https://speakerdeck.com/richardimaokajp/scala-ziowobatutichu-li-nishi-tutemita
  program:
    title: "Market positioning of Scala 3"
    length: 40分
    language: Japanese
    tags:
      - Others
    suggestions:
      - Scala 3
hiring
business
    detail: |
      Was Scala's marketing strategy wrong? Some newer languages attracted more developers, while Scala houses struggled to hire developers and the language couldn't sell its killer features very well. I'll discuss if Scala 3 changes this, analyzing other language's strategies and business trends.
```

- [ ] 日本語版の掲載
- [ ] 英語版の掲載

- 追加発表者の有無
```
自分一人。自分の他に発表者はいない。
```
- [ ] 追加発表者がいる場合には掲載する
