### ISSUE TITLE
[英語フォーム] CFPの和訳と掲載: Mateusz Sokół さんによる「ZIO Actors」

### ISSUE THREAD

**Issue by tomoco95** [scalamatsuri/2020.scalamatsuri.org#156]
```
id: "" # proposalは人名-No
ja:
  candidate:
    name: "Mateusz Sokół"
    twitter: https://twitter.com/mt_sokol
    github: https://github.com/mtsokol
    other_sns: 
    icon: https://www.functionalscala.com/css/2017_style/img/speaker/Mateusz_Sokol.jpg
    organization: Software Engineer at Scalac, Undergrad student at AGH - UST in Cracow
    contributes:
      - For the last six months I've been involved in OSS contribution to ZIO ecosystem - a concurrent programming library for Scala.
I've committed to ZIO, ZIO-NIO and ZIO-Actors where for ZIO-Actors I've done a library overhaul.

I'm the author of Actor System and Actor Remoting for ZIO-Actors which I've done from scratch under John De Goes and other ZIO organization members supervision.

Recently we've done first library release which was a big event on twitter:
https://twitter.com/SalarRahmanian/status/1203780952595394560
    speaker_experience:
      - I gave a talk at FunctionalScala 2019 (London edition) which was my first talk.

I'm listed as next to last speaker: https://www.functionalscala.com/

The talk I would like to give would be pretty much the same but extended with new parts that we will deliver in the next months. The original talk was planned for 25 min presentation.

A recording of my talk should be available soon, so you can evaluate whether it's suitable.

Current slides are available here: https://slides.com/mtsokol/zio-actors
  program:
    title: ""
    length: 40 minutes
    language: English
    tags:
      - Functional Programming, Tools
    keywords:
      - Actor Model
ZIO
Functional Programming
    detail: |
      
```

- 英語の情報
```
- title: ZIO Actors
- detail: Actors are one of the most popular concurrency models in nowadays software systems. In this talk, I will present zio-actors - a small, strongly typed actor library backed by ZIO. I will explain library design, demonstrate its usage and point out the differences and similarities with Akka.
```

- [ ] 和訳
- [ ] 日本語版の掲載

- 追加発表者の有無
```

```
  - [ ] Yesの場合には追加発表者を掲載する
