### ISSUE TITLE
[英語フォーム] CFPの掲載: Piotr Gawryśさんによる「Sleeping well in the lion's den with Monix Catnap」

### ISSUE THREAD

**Issue by tomoco95** [scalamatsuri/2020.scalamatsuri.org#159]
```
id: "" # proposalは人名-No
en:
  candidate:
    name: Piotr Gawryś
    twitter: https://twitter.com/p_gawrys
    github: https://github.com/Avasil
    other_sns: 
    icon: https://avatars3.githubusercontent.com/u/12383899?s=400&u=3f8d764e0dec2906239e2a846c45134ced27e2ec&v=4
    organization: Software Engineer at VirtusLab
    contributes:
      - Monix, Cats-Effect, Monix-BIO
    speaker_experience:
      - ScalaMatsuri 2019: https://www.youtube.com/watch?v=MeOs9SeO8-c
flatMap(Oslo) 2019: https://www.youtube.com/watch?v=InctntW3CAA

And the same talk on Scalar 2019
  program:
    title: "Sleeping well in the lion's den with Monix Catnap"
    length: 40 minutes
    language: English
    tags:
      - Functional Programming, Others
    keywords:
      - concurrency, fp, tracing
    detail: |
      Concurrency bugs leave you restless? Monix Catnap provides a ton of utilities that will let your worries take a good nap!

If you’re curious how Local can help you with tracing, had to solve complex producer-consumer scenarios or you ever needed a high-performance Async Queue it’s a talk for you.
```

- [ ] 英語版の掲載

- 追加発表者の有無
```

```
- [ ] Yesの場合には追加発表者を掲載する
