### ISSUE TITLE
[英語フォーム] CFPの和訳と掲載: Piotr Gawryś さんによる「Understanding Monix Observable」

### ISSUE THREAD

**Issue by tomoco95** [scalamatsuri/2020.scalamatsuri.org#161]
```
id: "" # proposalは人名-No
ja:
  candidate:
    name: "Piotr Gawryś"
    twitter: https://twitter.com/p_gawrys
    github: https://github.com/Avasil
    other_sns: 
    icon: https://avatars3.githubusercontent.com/u/12383899?s=400&u=3f8d764e0dec2906239e2a846c45134ced27e2ec&v=4
    organization: Software Engineer at VirtusLab
    contributes:
      - https://github.com/monix/monix
https://github.com/monix/monix-bio
https://github.com/typelevel/cats-effect
    speaker_experience:
      - ScalaMatsuri 2019: https://www.youtube.com/watch?v=MeOs9SeO8-c
flatMap(Oslo) 2019: https://www.youtube.com/watch?v=InctntW3CAA

And the same talk on Scalar 2019
  program:
    title: ""
    length: 100 minutes (contains 20 minutes' break in all)
    language: English
    tags:
      - Functional Programming, Software Design and Architecture, Others
    keywords:
      - Concurrency
Streaming
Internals
    detail: |
      
```

- 英語の情報
```
- title: Understanding Monix Observable
- detail: Monix Observable is a streaming data type which marries ReactiveX with purely functional programming in Scala.

Let’s dive deep into its internals, explain how and why it works and what are some of the less pleasant consequences of its design.
```

- [ ] 和訳
- [ ] 日本語版の掲載

- 追加発表者の有無
```

```
  - [ ] Yesの場合には追加発表者を掲載する
