### ISSUE TITLE
[英語フォーム] CFPの掲載: Alexey Novakovさんによる「Writing Kubernetes Operator with Cats-Effects」

### ISSUE THREAD

**Issue by tomoco95** [scalamatsuri/2020.scalamatsuri.org#171]
```
id: "" # proposalは人名-No
en:
  candidate:
    name: Alexey Novakov
    twitter: @alexey_novakov
    github: https://github.com/novakov-alexey
    other_sns: 
    icon: https://twitter.com/alexey_novakov/photo
    organization: Herr
    contributes:
      - 1. http4s-spnego: https://github.com/novakov-alexey/http4s-spnego
2. Kubernetes operator library: Freya - https://github.com/novakov-alexey/freya
3. fs2-kafka contribution: https://github.com/fd4s/fs2-kafka/pull/251
    speaker_experience:
      - 1. BOB Summer 2019: https://bobkonf.de/2019-summer/novakov.html
2. LXScala 2019: https://lxscala-reactive.com/speakers/alexey-novakov/
Slides: https://github.com/novakov-alexey/workshop-scala-msi-tpl/blob/master/slides/workshop-building-scala-microservice.pdf
3. Rhein-Main Scala Meetup: Asynchronous Data Processing with Reactive Streams and Akka 
https://www.meetup.com/Rhein-Main-Scala-Enthusiasts/events/244890805/
https://speakerdeck.com/alexeyn/scala-reactive-streams
  program:
    title: "Writing Kubernetes Operator with Cats-Effects"
    length: 40 minutes
    language: English
    tags:
      - Functional Programming, DevOps, Microservices
    keywords:
      - functional-programming, kubernetes, cats-effect
    detail: |
      Scala and Cats-Effects are perfect tools to implement functional backend application like Kubernetes(k8s) operator. In this talk we are going through K8s Operator implementation and introduction to a small, but helpful library in Scala using fabri8 k8s-client under the hood.
```

- [ ] 英語版の掲載

- 追加発表者の有無
```

```
- [ ] Yesの場合には追加発表者を掲載する
