### ISSUE TITLE
[英語フォーム] CFPの掲載: TOMOKO TAKAHASHIさんによる「test」

### ISSUE THREAD

**Issue by tomoco95** [scalamatsuri/2020.scalamatsuri.org#18]
```
id: "" # proposalは人名-No
en:
  candidate:
    name: TOMOKO TAKAHASHI
    twitter: scalamatsuri
    github: tomoco95
    icon:  https://twitter.com/scalamatsuri
    organization: JSA
    contributes:
      - test1
test2
test3
    speaker_experience:
      - test1
test2
test3
  program:
    title: "test"
    length: 100 minutes (contains 20 minutes' break in all)
    language: English
    tags:
      - Big Data / Fast Data, Software Design and Architecture
    suggestions:
      - - test1
- test2
- test3
    detail: |
      test test test
```

- [ ] 英語版の掲載

- 追加発表者の有無
```

```
- [ ] Yesの場合には追加発表者を掲載する
