### ISSUE TITLE
[英語フォーム] CFPの和訳と掲載: Daniel Beskin さんによる「Sharing Is Caring - How to Let the Compiler Know What You're Thinking」

### ISSUE THREAD

**Issue by tomoco95** [scalamatsuri/2020.scalamatsuri.org#181]
```
id: "" # proposalは人名-No
ja:
  candidate:
    name: "Daniel Beskin"
    twitter: 
    github: ncreep
    other_sns: 
    icon: https://avatars2.githubusercontent.com/u/784734
    organization: 
    contributes:
      - - "What Orwell's 1984 Can Teach Us about Programming"
  Slides: https://ncreep.github.io/1984-talk/presentation/presentation.html
  Lambda Days, 2017, Poland: https://www.youtube.com/watch?v=nRZuSZZBzoI
  LambdaConf, 2017, US: https://www.youtube.com/watch?v=5UWzGbf04so
  Scala Swarm, 2017, Portugal: https://www.youtube.com/watch?v=jjIfvbkSKGU
  Scala IO,  2017, France: https://www.youtube.com/watch?v=QDaIC6OD6sU

- "Compile Time Logic Programming in Scala - What For?"
  Slides: https://ncreep.github.io/compile-time-logic-programming-talk/presentation/presentation.html
  Scala eXchange, 2017, UK: https://skillsmatter.com/skillscasts/10957-compile-time-logic-programming-in-scala-what-for
  ScalaUA, 2019, Ukraine: https://www.youtube.com/watch?v=wHrdrRvC1Wg
  ScalaWorld 2019, UK: https://www.youtube.com/watch?v=9i06TyYM_lI

- "Sharing Is Caring - How to Let the Compiler Know What You're Thinking"
  Slides: https://ncreep.github.io/sharing-is-caring-talk/presentation/presentation.html
  BeeScala, 2017, Slovenia: https://www.youtube.com/watch?v=Slu_PYZlcUA
  Scala IO, 2018, France: https://www.youtube.com/watch?v=GsXVxhKpUwI

- "Category Theory as a Tool for Thought"
  Slides: https://github.com/ncreep/category-theory-as-a-tool-for-thought
  LambdaConf 2019, US
    speaker_experience:
      - 
  program:
    title: ""
    length: 40 minutes
    language: English
    tags:
      - Functional Programming, Best Practices, Software Design and Architecture
    keywords:
      - FP
Types
    detail: |
      
```

- 英語の情報
```
- title: Sharing Is Caring - How to Let the Compiler Know What You're Thinking
- detail: As Scala developers, it is not uncommon to find ourselves struggling against the compiler. And although the compiler tries to communicate with us, the result can be both incomprehensible and one-sided. 

In this beginner-friendly talk, we will see how we can improve things by sharing our thoughts with the compiler - be it by using more descriptive types, leveraging implicits, or even churning out some macros. By this simple act of sharing, we can elevate our relationship with the compiler into a meaningful, and hopefully productive, dialog.
```

- [ ] 和訳
- [ ] 日本語版の掲載

- 追加発表者の有無
```

```
  - [ ] Yesの場合には追加発表者を掲載する
