### ISSUE TITLE
[英語フォーム] CFPの和訳と掲載: Vincent de Haan さんによる「Functional programming and the JVM」

### ISSUE THREAD

**Issue by tomoco95** [scalamatsuri/2020.scalamatsuri.org#191]
```
id: "" # proposalは人名-No
ja:
  candidate:
    name: "Vincent de Haan"
    twitter: 
    github: https://github.com/vincentdehaan
    other_sns: 
    icon: https://media-exp2.licdn.com/dms/image/C4D03AQGsxuQhXLqvhg/profile-displayphoto-shrink_200_200/0?e=1584576000&v=beta&t=-VzPC1l1jPc0g5_ggG0zYK_klBzEWD2L7cGyPg81hUc
    organization: Ordina, software engineer
    contributes:
      - 
    speaker_experience:
      - LX Scala & Reactive 2019: https://lxscala-reactive.com/speakers/vincent-de-haan/
In company conferences
I have teaching experience with university level math courses
  program:
    title: ""
    length: 40 minutes
    language: English
    tags:
      - Functional Programming
    keywords:
      - performance
jvm
    detail: |
      
```

- 英語の情報
```
- title: Functional programming and the JVM
- detail: Functional programming has a lot of advantages, but it does not fit naturally on the metal of our machines. Did you ever wonder how functional Scala code is run on the JVM? In this talk we will look at the way functional abstractions are translated to bytecode, and what this means for performance.
```

- [ ] 和訳
- [ ] 日本語版の掲載

- 追加発表者の有無
```

```
  - [ ] Yesの場合には追加発表者を掲載する
