### ISSUE TITLE
[英語フォーム] CFPの掲載: Vincent de Haanさんによる「Functional programming and the JVM」

### ISSUE THREAD

**Issue by tomoco95** [scalamatsuri/2020.scalamatsuri.org#193]
```
id: "" # proposalは人名-No
en:
  candidate:
    name: Vincent de Haan
    twitter: 
    github: https://github.com/vincentdehaan
    other_sns: 
    icon: https://media-exp2.licdn.com/dms/image/C4D03AQGsxuQhXLqvhg/profile-displayphoto-shrink_200_200/0?e=1584576000&v=beta&t=-VzPC1l1jPc0g5_ggG0zYK_klBzEWD2L7cGyPg81hUc
    organization: Ordina, software engineer
    contributes:
      - 
    speaker_experience:
      - LX Scala & Reactive 2019: https://lxscala-reactive.com/speakers/vincent-de-haan/
In company conferences
I have teaching experience with university level math courses
  program:
    title: "Functional programming and the JVM"
    length: 40 minutes
    language: English
    tags:
      - Functional Programming
    keywords:
      - performance
jvm
    detail: |
      Functional programming has a lot of advantages, but it does not fit naturally on the metal of our machines. Did you ever wonder how functional Scala code is run on the JVM? In this talk we will look at the way functional abstractions are translated to bytecode, and what this means for performance.
```

- [ ] 英語版の掲載

- 追加発表者の有無
```

```
- [ ] Yesの場合には追加発表者を掲載する
