### ISSUE TITLE
[英語フォーム] CFPの和訳と掲載: Idrees Khan さんによる「Expectations vs Reality: Working with Data @ Spotify」

### ISSUE THREAD

**Issue by tomoco95** [scalamatsuri/2020.scalamatsuri.org#195]
```
id: "" # proposalは人名-No
ja:
  candidate:
    name: "Idrees Khan"
    twitter: https://twitter.com/idreesxkhan
    github: https://github.com/idreeskhan
    other_sns: 
    icon: https://drive.google.com/open?id=1Gws8tKdrh9Mx_b_7aPbiqkzXUKVL58oc
    organization: Senior Data Infrastructure Engineer at Spotify
    contributes:
      - https://github.com/spotify/ratatool
    speaker_experience:
      - I have presented at
Scale By The Bay Oakland 2019 - https://www.youtube.com/watch?v=lRpB76CXMd4
NABD Paris 2019
Scala Up North Toronto 2018 - https://www.youtube.com/watch?v=SOLM8t5snGM
  program:
    title: ""
    length: 40 minutes
    language: English
    tags:
      - Big Data / Fast Data, Best Practices
    keywords:
      - Big Data
Typeclass Derivation
Pipeline Testing
    detail: |
      
```

- 英語の情報
```
- title: Expectations vs Reality: Working with Data @ Spotify
- detail: In the real-world, datasets don’t always conform to our expectations. We will discuss tools that have been built at Spotify to help data producers and consumers better understand the contents of data they are working with, and standardize the process of working with data across a large and complex organization.
```

- [ ] 和訳
- [ ] 日本語版の掲載

- 追加発表者の有無
```

```
  - [ ] Yesの場合には追加発表者を掲載する
