### ISSUE TITLE
[英語フォーム] CFPの和訳と掲載: TOMOKO TAKAHASHI さんによる「test」

### ISSUE THREAD

**Issue by tomoco95** [scalamatsuri/2020.scalamatsuri.org#2]
```
id: "" # proposalは人名-No
ja:
  candidate:
    name: "TOMOKO TAKAHASHI"
    twitter: scalamatsuri
    github: tomoco95
    icon:  https://twitter.com/scalamatsuri
    organization: JSA
    contributes:
      - ""
      test1
test2
test3
    speaker_experience:
      - ""
      test1
test2
test3
  program:
    title: "テストのタイトル"
    length: 100 minutes (contains 20 minutes' break in all)
    language: English
    tags:
      - ""
      Big Data / Fast Data, Software Design and Architecture
    suggestions:
      - ""
      - test1
- test2
- test3
    detail: |
      てすとてすとてすと
```

- 英語の情報
```
- title: test
- detail: test test test
```

- [ ] 和訳
- [ ] 日本語版の掲載

- 追加発表者の有無：（要レビュー）Yes. The session has some additional presenters.
  - [ ] Yesの場合には追加発表者を追加する
