### ISSUE TITLE
[日本語フォーム] CFPの掲載:  近藤 豊峰さんによる「Page Speed Insights 改善虎の巻 ~ Scala祭りページを高速化するまで ~ (仮)」

### ISSUE THREAD

**Issue by tomoco95** [scalamatsuri/2020.scalamatsuri.org#20]
```
id: "" # proposalは人名-No
ja:
  candidate:
    name: "近藤 豊峰"
    twitter: sugoikondo
    github: sugoikondo
    icon: https://avatars2.githubusercontent.com/u/16359063?s=460&v=4
    organization: 株式会社セプテーニ・オリジナル
    contributes:
      - ScalaMatsuri2020
Elm-jp
    speaker_experience:
     - Jser.info
  program:
    title: "Page Speed Insights 改善虎の巻 ~ Scala祭りページを高速化するまで ~ (仮)"
    length: 100分（合計20分の休憩を含む）
    language: Japanese
    tags:
      - Others
    suggestions:
      - Page Speed Insights
Nuxt.js
Performance Optimization
    detail: |
      Scalaまつり公式サイトを2020年にリニューアルするに伴い、パフォーマンスの改善にも挑戦しました。所謂キャッシュのうまい付き合い方とか、jsの高効率な書き方とかの話はできませんが、画像の最適化やコードの分割方法、その他表示速度の改善について得られた知見を共有したいと思います。
en:
  candidate:
    name: Atsumine Kondo
    twitter: sugoikondo
    github: sugoikondo
    icon: https://avatars2.githubusercontent.com/u/16359063?s=460&v=4
    organization: 株式会社セプテーニ・オリジナル
    contributes:
      - ScalaMatsuri2020
Elm-jp
    speaker_experience:
      - Jser.info
  program:
    title: "Page Speed Insights refinement 101"
    length: 100分（合計20分の休憩を含む）
    language: Japanese
    tags:
      - Others
    suggestions:
      - Page Speed Insights
Nuxt.js
Performance Optimization
    detail: |
      In developing new ScalaMatsuri2020 website, we tried to improve its performance for better user experience.I can't speak about caching, efficient style coding, but I will tell you about it's importance about optimizing images, or minifying javascript codes or runtime executions.
```

- [ ] 日本語版の掲載
- [ ] 英語版の掲載

- 追加発表者の有無
```
自分一人。自分の他に発表者はいない。
```
- [ ] 追加発表者がいる場合には掲載する
