### ISSUE TITLE
[英語フォーム] CFPの和訳と掲載: sugoikondo さんによる「Page Speed Insigts Optimization 101」

### ISSUE THREAD

**Issue by tomoco95** [scalamatsuri/2020.scalamatsuri.org#21]
```
id: "" # proposalは人名-No
ja:
  candidate:
    name: "sugoikondo"
    twitter: sugoikondo
    github: sugoikondo
    icon: https://avatars2.githubusercontent.com/u/16359063?s=460&v=4
    organization: Septeni Original Inc.
    contributes:
      - Nothig!
    speaker_experience:
      - No! This is my first time!
  program:
    title: "Oh, sorry! I can't write in Japanese! Sushi! Samurai! Hahaha!!"
    length: 40 minutes
    language: English
    tags:
      - Others
    suggestions:
      - 
    detail: |
      
```

- 英語の情報
```
- title: Page Speed Insigts Optimization 101
- detail: In developing new ScalaMatsuri2020 website, we tried to improve its performance for better user experience.I can't speak about caching, efficient style coding, but I will tell you about it's importance about optimizing images, or minifying javascript codes or runtime executions.
```

- [ ] 和訳
- [ ] 日本語版の掲載

- 追加発表者の有無
```

```
  - [ ] Yesの場合には追加発表者を掲載する
