### ISSUE TITLE
[英語フォーム] CFPの掲載: Jakub Kozłowskiさんによる「Keep your sanity with compositional tracing」

### ISSUE THREAD

**Issue by tomoco95** [scalamatsuri/2020.scalamatsuri.org#226]
```
id: "" # proposalは人名-No
en:
  candidate:
    name: Jakub Kozłowski
    twitter: kubukoz
    github: kubukoz
    other_sns: 
    icon: https://blog.kubukoz.com/assets/images/kubukoz.jpg
    organization: 
    contributes:
      - I help maintain fs2 and redis4cats, sometimes I commit to cats-effect.
    speaker_experience:
      - I spoke at Scalar, Scala World and Functional Scala (London). Here are the videos:

https://www.youtube.com/watch?v=oluPEFlXumw
https://www.youtube.com/watch?v=EQWAQF6Yj5Q
https://www.youtube.com/watch?v=fZO2lV2xjEo
  program:
    title: "Keep your sanity with compositional tracing"
    length: 40 minutes
    language: English
    tags:
      - Functional Programming, Best Practices, Microservices
    keywords:
      - distributed systems, tracing, microservices
    detail: |
      Logging is not enough for building distributed systems that you can investigate in case of production issues (which will happen). As an alternative, we can use tracing.

I’ll go through a process of implementing tracing, starting with the simplest approach and going to a more compositional one.
```

- [ ] 英語版の掲載

- 追加発表者の有無
```

```
- [ ] Yesの場合には追加発表者を掲載する
