### ISSUE TITLE
[英語フォーム] CFPの掲載: Jakub Kozłowskiさんによる「A sky full of streams - embracing compositionality of functional streams」

### ISSUE THREAD

**Issue by tomoco95** [scalamatsuri/2020.scalamatsuri.org#228]
```
id: "" # proposalは人名-No
en:
  candidate:
    name: Jakub Kozłowski
    twitter: kubukoz
    github: kubukoz
    other_sns: 
    icon: https://blog.kubukoz.com/assets/images/kubukoz.jpg
    organization: 
    contributes:
      - I help maintain fs2 and redis4cats, and I sometimes contribute to cats-effect.
    speaker_experience:
      - I spoke at Scala Italy, Scalar and flatMap(Oslo).

Videos:
https://vimeo.com/368027707
https://www.youtube.com/watch?v=fZO2lV2xjEo
https://www.youtube.com/watch?v=HMs_F7LXTak
  program:
    title: "A sky full of streams - embracing compositionality of functional streams"
    length: 40 minutes
    language: English
    tags:
      - Functional Programming, Microservices
    keywords:
      - streaming
concurrency
functional programming
    detail: |
      Streaming sounds like a complicated concept, but the core principles can actually be relatively easy to understand. I would like to show what a functional streaming library looks like and how FS2 can simplify some of the things we often do in concurrent systems.
```

- [ ] 英語版の掲載

- 追加発表者の有無
```

```
- [ ] Yesの場合には追加発表者を掲載する
