### ISSUE TITLE
[日本語フォーム] CFPの掲載:  高橋 知子(表示される氏名)さんによる「バックオフィスでScala使ってみた話をします。(すみません、テストデータです。)」

### ISSUE THREAD

**Issue by tomoco95** [scalamatsuri/2020.scalamatsuri.org#23]
```
id: "" # proposalは人名-No
ja:
  candidate:
    name: "高橋 知子(表示される氏名)"
    twitter: scalamatsuri
    github: tomoco95
    other_sns: facebook
    icon: https://twitter.com/scalamatsuri
    organization: JSA バックオフィスチーム
    contributes:
      - ScalaMatsuri2020
ScalaMatsuri2019
    speaker_experience:
     - - ScalaMatsuri2017
- ScalaMatsuri2018
- ScalaMatsuri2019
  program:
    title: "バックオフィスでScala使ってみた話をします。(すみません、テストデータです。)"
    length: 40分
    language: Japanese
    tags:
      - Big Data / Fast Data, Software Design and Architecture, Others
    suggestions:
      - Page Speed Insights
Nuxt.js
Performance Optimization
    detail: |
      バックオフィスでScala使ってみた話をします。(すみません、テストデータです。)
en:
  candidate:
    name: Tomoko Takahashi
    twitter: scalamatsuri
    github: tomoco95
    other_sns: facebook
    icon: https://twitter.com/scalamatsuri
    organization: JSA バックオフィスチーム
    contributes:
      - ScalaMatsuri2020
ScalaMatsuri2019
    speaker_experience:
      - - ScalaMatsuri2017
- ScalaMatsuri2018
- ScalaMatsuri2019
  program:
    title: "(test)バックオフィスでScala使ってみた(実際には英語タイトルが入ります)"
    length: 40分
    language: Japanese
    tags:
      - Big Data / Fast Data, Software Design and Architecture, Others
    suggestions:
      - Page Speed Insights
Nuxt.js
Performance Optimization
    detail: |
      (実際には英語のセッション概要が入ります)バックオフィスでScala使ってみた話をします。(すみません、テストデータです。)
```

- [ ] 日本語版の掲載
- [ ] 英語版の掲載

- 追加発表者の有無
```
自分一人。自分の他に発表者はいない。
```
- [ ] 追加発表者がいる場合には掲載する
