### ISSUE TITLE
[英語フォーム] CFPの掲載: Alexey Kotlyarovさんによる「This is Not a Monad Tutorial」

### ISSUE THREAD

**Issue by tomoco95** [scalamatsuri/2020.scalamatsuri.org#230]
```
id: "" # proposalは人名-No
en:
  candidate:
    name: Alexey Kotlyarov
    twitter: koterpillar
    github: koterpillar
    other_sns: 
    icon: https://pbs.twimg.com/profile_images/1221297488096681985/ElNbYS7D_400x400.jpg
    organization: 
    contributes:
      - I'm developing Serverless Haskell together with my colleagues at SEEK: https://github.com/seek-oss/serverless-haskell/
I've also submitted patches to Circe and other Scala libraries.
    speaker_experience:
      - Most recent conference was YOW! Lambda Jam: https://yowconference.com/talks/alexey-kotlyarov/yow-lambda-jam-2017/instances-for-everyone-free-generic-programming-in-haskell-12485/
Apart from that, I've had presentations on Melbourne Scala User Group: https://www.meetup.com/Melbourne-Scala-User-Group/events/258778805/
Melbourne Haskell User Group: https://www.meetup.com/Melbourne-Haskell-Users-Group/events/qfptslyxdbdc/
  program:
    title: "This is Not a Monad Tutorial"
    length: 40 minutes
    language: English
    tags:
      - Functional Programming, Scala Beginners (~1year)
    keywords:
      - typeclasses
laws
    detail: |
      Abstractions like Monad are often explained by examples for common types like Option. This talk explains Functor, Monad and other abstractions by showing where they are impossible to implement, exposing their laws and structure and building understanding of the guarantees they provide.
```

- [ ] 英語版の掲載

- 追加発表者の有無
```

```
- [ ] Yesの場合には追加発表者を掲載する
