### ISSUE TITLE
[日本語フォーム] CFPの掲載:  石橋隆平さんによる「Scala初心者にこそお勧めしたいZIO」

### ISSUE THREAD

**Issue by tomoco95** [scalamatsuri/2020.scalamatsuri.org#231]
```
id: "" # proposalは人名-No
ja:
  candidate:
    name: "石橋隆平"
    twitter: https://twitter.com/cactaceae
    github: https://github.com/rysh
    other_sns: 
    icon: https://gravatar.com/avatar/184bb1d4907877239bd4f9ddeb5f1283?s=80&d=robohash&r=x
    organization: Software developer at StanBy
    contributes:
      - 
    speaker_experience:
     - 
  program:
    title: "Scala初心者にこそお勧めしたいZIO"
    length: 40分
    language: Japanese
    tags:
      - Functional Programming, Best Practices, Scalaビギナー（Scala歴1年くらいまで）
    keywords:
      - Effect System, ZIO, Concurrency
    detail: |
      ScalaのEffect Systemは選択肢が多数あり、Scala初心者が適切に選択することは難しい状況があります。Scala初心者や熟練者が少ないチームのファーストチョイスとしてZIOをお勧めしたいと思っています。基本的な使い方、初心者にお勧めする理由、プロジェクトへの導入のポイントなどを理解しいやすいコードとともに紹介したいと思います。
en:
  candidate:
    name: Ishibashi Ryuhei
    twitter: https://twitter.com/cactaceae
    github: https://github.com/rysh
    other_sns: 
    icon: https://gravatar.com/avatar/184bb1d4907877239bd4f9ddeb5f1283?s=80&d=robohash&r=x
    organization: Software developer at StanBy
    contributes:
      - 
    speaker_experience:
      - 
  program:
    title: "ZIO Introduction for Scala beginners"
    length: 40分
    language: Japanese
    tags:
      - Functional Programming, Best Practices, Scalaビギナー（Scala歴1年くらいまで）
    suggestions:
      - Effect System, ZIO, Concurrency
    detail: |
      Scala's Effect Systems has many choices, and there are situations where it is difficult for beginners to use Scala. I would recommend ZIO as the first choice for a team with Scala beginners. I will introduce basic usage, reasons to recommend, points of introducing into project, etc. with easy code.
```

- [ ] 日本語版の掲載
- [ ] 英語版の掲載

- 追加発表者の有無
```
自分一人。自分の他に発表者はいない。
```
- [ ] 追加発表者がいる場合には掲載する
