### ISSUE TITLE
[日本語フォーム] CFPの掲載:  市川 和央 @phenanさんによる「文字列補間の応用による直感的双方向文字列処理」

### ISSUE THREAD

**Issue by tomoco95** [scalamatsuri/2020.scalamatsuri.org#232]
```
id: "" # proposalは人名-No
ja:
  candidate:
    name: "市川 和央 @phenan"
    twitter: phenan
    github: phenan
    other_sns: 
    icon: https://twitter.com/phenan/photo
    organization: LINE株式会社 エンジニア
    contributes:
      - 
    speaker_experience:
     - ScalaMatsuri2019 Scala における型クラス入門
ScalaMatsuri2018 Scalaの言語機構を悪用して最強のDSLを作る方法
<Programming> 2017 User-Defined Operators Including Name Binding for New Language Constructs https://programming-journal.org/2017/1/15/
  program:
    title: "文字列補間の応用による直感的双方向文字列処理"
    length: 40分
    language: Japanese
    tags:
      - Functional Programming
    keywords:
      - DSL
bi-directional
generics
    detail: |
      アプリケーションでは文字列を読み出す処理しかしない場合でも、テストの入力を作る場合には文字列を組み立てる処理を実装しなければならなくなることはよくある。
そのような場合のための、文字列の読み出しと組み立てを同時に実装する手法を紹介する。
また、文字列補間(String Interpolation)を活用することで、非常に直感的な記法で記述が可能であることを示す。
en:
  candidate:
    name: Kazuhiro Ichikawa
    twitter: phenan
    github: phenan
    other_sns: 
    icon: https://twitter.com/phenan/photo
    organization: LINE株式会社 エンジニア
    contributes:
      - 
    speaker_experience:
      - ScalaMatsuri2019 Scala における型クラス入門
ScalaMatsuri2018 Scalaの言語機構を悪用して最強のDSLを作る方法
<Programming> 2017 User-Defined Operators Including Name Binding for New Language Constructs https://programming-journal.org/2017/1/15/
  program:
    title: "Intuitive bidirectional string processing by string interpolation in Scala"
    length: 40分
    language: Japanese
    tags:
      - Functional Programming
    suggestions:
      - DSL
bi-directional
generics
    detail: |
      Even if an application only has to parse a string, it is often necessary to implement pretty-printing when creating test inputs.
In this presentation, we show our method to implement parsing and pretty-printing of strings at the same time.
We also show that it is possible to describe in a very intuitive notation by utilizing string interpolation.
```

- [ ] 日本語版の掲載
- [ ] 英語版の掲載

- 追加発表者の有無
```
自分一人。自分の他に発表者はいない。
```
- [ ] 追加発表者がいる場合には掲載する
