### ISSUE TITLE
[日本語フォーム] CFPの掲載:  かとじゅんさんによる「Scalaで解説する、ビジネスパターンによるモデル駆動設計」

### ISSUE THREAD

**Issue by tomoco95** [scalamatsuri/2020.scalamatsuri.org#233]
```
id: "" # proposalは人名-No
ja:
  candidate:
    name: "かとじゅん"
    twitter: j5ik2o
    github: j5ik2o
    other_sns: twiiter
    icon: https://twitter.com/j5ik2o/photo
    organization: Chatwork株式会社 テックリード
    contributes:
      - 
    speaker_experience:
     - ScalaMatsuri 2019, AWS DevDay など
  program:
    title: "Scalaで解説する、ビジネスパターンによるモデル駆動設計"
    length: 40分
    language: Japanese
    tags:
      - Software Design and Architecture
    keywords:
      - DDD Modeling REA
    detail: |
       2007年発刊のPavel Hruby著「ビジネスパターンによるモデル駆動設計」はドメイン駆動設計に関連する有益なパターンを提供している書籍です。この書籍ではREA(Resource, Event, Agent)というビジネスアプリケーションにおいて普遍的なモデリングパターンを紹介しています。こういったREA構造を基に期日や分類などの振る舞いのパターンも役に立ちます。10年に考案されたこれらのパターンをScalaで現代に再現するにはどうするべきか、私は興味を持っています。REAからいくつかのパターンを抜粋して議論したいと思います。
en:
  candidate:
    name: Junichi Kato
    twitter: j5ik2o
    github: j5ik2o
    other_sns: twiiter
    icon: https://twitter.com/j5ik2o/photo
    organization: Chatwork株式会社 テックリード
    contributes:
      - 
    speaker_experience:
      - ScalaMatsuri 2019, AWS DevDay など
  program:
    title: " Explain model-driven design based on business patterns using Scala"
    length: 40分
    language: Japanese
    tags:
      - Software Design and Architecture
    suggestions:
      - DDD Modeling REA
    detail: |
      "Model-Driven Design Using Business Patterns" by Pavel Hruby published in 2006 is a book that provides useful patterns related to Domain-Driven Design(DDD). This book introduces universal modeling patterns for business applications called REA (Resource, Event, Agent).
Based on these REA structures, behavior patterns such as "date" and "classification" are also useful. I'm interested in how Scala expresses the patterns invented 10 years ago. This time I want to discuss some patterns from REA.
```

- [ ] 日本語版の掲載
- [ ] 英語版の掲載

- 追加発表者の有無
```
自分一人。自分の他に発表者はいない。
```
- [ ] 追加発表者がいる場合には掲載する
