### ISSUE TITLE
[英語フォーム] CFPの掲載: Olivier Blanvillainさんによる「Fast Type Classes with Dotty Macros」

### ISSUE THREAD

**Issue by tomoco95** [scalamatsuri/2020.scalamatsuri.org#236]
```
id: "" # proposalは人名-No
en:
  candidate:
    name: Olivier Blanvillain
    twitter: 
    github: https://github.com/OlivierBlanvillain
    other_sns: 
    icon: https://people.epfl.ch/private/common/photos/links/184098.jpg?ts=1578816841
    organization: EPFL
    contributes:
      - Dotty compiler, Frameless, monadic-html
    speaker_experience:
      - Scala Days 2018 (speaker 1) https://slideslive.com/38908156/applications-of-implicit-function-types
ML Days Tokyo (speaker 2) https://speakerdeck.com/biboudis/highest-performance-stream-processing-in-meta-ocaml-and-scala-3
  program:
    title: "Fast Type Classes with Dotty Macros"
    length: 40 minutes
    language: English
    tags:
      - Functional Programming, Software Design and Architecture
    keywords:
      - dotty
macros
type-class-derivation
    detail: |
      Dotty brings first class support for type class derivation, but the resulting instances can be slow at runtime. We give an introduction to Dotty macros and take a look at how we can leverage them to implement an optimized version of type class derivation.
```

- [ ] 英語版の掲載

- 追加発表者の有無
```
I am.
```
- [ ] Yesの場合には追加発表者を掲載する
