### ISSUE TITLE
追加発表者の掲載: 「Fast Type Classes with Dotty Macros」

### ISSUE THREAD

**Issue by tomoco95** [scalamatsuri/2020.scalamatsuri.org#237]
```
  candidate:
    name: ""
    twitter: https://twitter.com/biboudis
    github: https://github.com/biboudis
    other_sns: https://www.instagram.com/aggelos_bibou/
https://ch.linkedin.com/in/biboudis?trk=author_mini-profile_title
    icon: https://media-exp1.licdn.com/dms/image/C5603AQFzMa7v7WEQBg/profile-displayphoto-shrink_200_200/0?e=1585180800&v=beta&t=7LEdc9xdoyeo-tv13C9afwVUMgrEyGR7AEYo8f25DEs
    organization: EPFL - Post Doc
    contributes:
      - Dotty, strymonas.github.io
    speaker_experience:
      - POPL 2017 https://www.youtube.com/watch?v=ifMC8ysmQz8
ECOOP 2015 https://www.youtube.com/watch?v=rHzgkMW2AZ0
  program:
    title: "Fast Type Classes with Dotty Macros"
```

- 英語の情報
```
- name: Aggelos Biboudis
```

- [ ] 追加発表者の掲載
