### ISSUE TITLE
[英語フォーム] CFPの掲載: Pierre Ricadatさんによる「Caliban: Designing a Functional GraphQL Library」

### ISSUE THREAD

**Issue by tomoco95** [scalamatsuri/2020.scalamatsuri.org#239]
```
id: "" # proposalは人名-No
en:
  candidate:
    name: Pierre Ricadat
    twitter: https://twitter.com/ghostdogpr
    github: https://github.com/ghostdogpr
    other_sns: 
    icon: https://www.functionalscala.com/css/2017_style/img/speaker/Pierre_Ricadat.jpg
    organization: 
    contributes:
      - https://github.com/ghostdogpr/caliban
https://github.com/zio/zio
https://github.com/zio/zio-akka-cluster
    speaker_experience:
      - Functional Scala 2019 (London)
video: https://www.youtube.com/watch?v=OC8PbviYUlQ
slides: https://www.slideshare.net/PierreRicadat/designing-a-functional-graphql-library-204680947
  program:
    title: "Caliban: Designing a Functional GraphQL Library"
    length: 40 minutes
    language: English
    tags:
      - Functional Programming, Software Design and Architecture
    keywords:
      - GraphQL
FP
ZIO
    detail: |
      GraphQL is becoming a strong alternative to REST for exposing APIs. In this talk, I will introduce Caliban, a new functional library for writing GraphQL backends in Scala. I will go through the process of creating the library from scratch and explain my design choices: how to minimize boilerplate, how to expose a pure API with explicit errors, how to handle subscriptions, etc.
```

- [ ] 英語版の掲載

- 追加発表者の有無
```

```
- [ ] Yesの場合には追加発表者を掲載する
