### ISSUE TITLE
[英語フォーム] CFPの和訳と掲載: Mikhail Limanskiy さんによる「Looking for the Needle in a Haystack of Dirty Data」

### ISSUE THREAD

**Issue by tomoco95** [scalamatsuri/2020.scalamatsuri.org#250]
```
id: "" # proposalは人名-No
ja:
  candidate:
    name: "Mikhail Limanskiy"
    twitter: https://twitter.com/mike_limansky
    github: https://github.com/limansky/
    other_sns: Facebook: https://www.facebook.com/mike.limansky
    icon: http://www.limansky.me/images/mikhail400x400.jpg
    organization: Senior Scala Developer, 1-OFD
    contributes:
      - 
    speaker_experience:
      - ScalaDays 2015 https://www.youtube.com/watch?v=5VNgXyefLso
BeeScala 2017 https://www.youtube.com/watch?v=v_RuP218y4k
ScalaConf 2019 (in Russian) https://www.youtube.com/watch?v=kw8PuCz3csI
  program:
    title: ""
    length: 40 minutes
    language: English
    tags:
      - Big Data / Fast Data, Software Design and Architecture
    keywords:
      - Big Data
HBase
Spark
    detail: |
      
```

- 英語の情報
```
- title: Looking for the Needle in a Haystack of Dirty Data
- detail: How could you possibly analyze a database of tens of billions of transactions containing really dirty data? And how to be fast on limited resources? At 1-OFD we do it every day with an open-source platform we created to get the job done. It’s a time-series storage on top of HBase, Akka and Spark.
```

- [ ] 和訳
- [ ] 日本語版の掲載

- 追加発表者の有無
```

```
  - [ ] Yesの場合には追加発表者を掲載する
