### ISSUE TITLE
[英語フォーム] CFPの和訳と掲載: Georg Schmid さんによる「First-Class Type-Level Programming」

### ISSUE THREAD

**Issue by tomoco95** [scalamatsuri/2020.scalamatsuri.org#254]
```
id: "" # proposalは人名-No
ja:
  candidate:
    name: "Georg Schmid"
    twitter: 
    github: gsps
    other_sns: 
    icon: https://avatars2.githubusercontent.com/u/2364189?s=460&v=4
    organization: EPFL
    contributes:
      - Dotty, Stainless, V8
    speaker_experience:
      - 
  program:
    title: ""
    length: 40 minutes
    language: English
    tags:
      - Functional Programming, Others
    keywords:
      - type-level programming
match types
dependent types
    detail: |
      
```

- 英語の情報
```
- title: First-Class Type-Level Programming
- detail: Scala already supports type-level programming through implicits, but can we do better? In this talk we introduce "match types", i.e., type functions, arriving in Scala 3.0 and some of their use cases. We also explore how the language could evolve to support fully-fledged dependent types.
```

- [ ] 和訳
- [ ] 日本語版の掲載

- 追加発表者の有無
```
I am.
```
  - [ ] Yesの場合には追加発表者を掲載する
