### ISSUE TITLE
追加発表者の掲載: 「First-Class Type-Level Programming」

### ISSUE THREAD

**Issue by tomoco95** [scalamatsuri/2020.scalamatsuri.org#256]
```
  candidate:
    name: ""
    twitter: 
    github: olivierblanvillain
    other_sns: 
    icon: https://people.epfl.ch/private/common/photos/links/184098.jpg
    organization: EPFL
    contributes:
      - Dotty, Frameless, Monadic-html
    speaker_experience:
      - Scala Days Berlin 2018
  program:
    title: "First-Class Type-Level Programming"
```

- 英語の情報
```
- name: Olivier Blanvillain
```

- [ ] 追加発表者の掲載
