### ISSUE TITLE
[英語フォーム] CFPの掲載: Paweł Jurczenkoさんによる「Modern JVM Multithreading」

### ISSUE THREAD

**Issue by tomoco95** [scalamatsuri/2020.scalamatsuri.org#258]
```
id: "" # proposalは人名-No
en:
  candidate:
    name: Paweł Jurczenko
    twitter: https://twitter.com/pawel_jurczenko
    github: https://github.com/pjurczenko
    other_sns: 
    icon: https://avatars.githubusercontent.com/u/12970160
    organization: Software Engineer at Allegro.pl
    contributes:
      - 
    speaker_experience:
      - 1. Allegro Tech Meeting 2019: https://youtu.be/Wjg3UxYmw3I
2. Poznań Java User Group: https://youtu.be/uBIKmB0NyGE
3. Allegro Tech Talks #19: https://www.facebook.com/allegro.tech/videos/446254389281330
  program:
    title: "Modern JVM Multithreading"
    length: 100 minutes (contains 20 minutes' break in all)
    language: English
    tags:
      - Best Practices, Software Design and Architecture
    keywords:
      - Multithreading
Concurrency
Reactive
    detail: |
      In this presentation I will show what might be taken into consideration when writing a modern JVM application using Scala language. What are the differences between green threads and fibers? What kind of thread pools and how many of them should be used? Can we have a non-blocking communication with relational databases? Can we decouple our domain logic from asynchrony? Is it possible to have a reasonable stack-trace in asynchronous code? These are the main questions I'd like to address in the presentation.
```

- [ ] 英語版の掲載

- 追加発表者の有無
```

```
- [ ] Yesの場合には追加発表者を掲載する
