### ISSUE TITLE
[英語フォーム] CFPの和訳と掲載: Michal Kowalczykiewicz さんによる「Back to the Future」

### ISSUE THREAD

**Issue by tomoco95** [scalamatsuri/2020.scalamatsuri.org#259]
```
id: "" # proposalは人名-No
ja:
  candidate:
    name: "Michal Kowalczykiewicz"
    twitter: 
    github: 
    other_sns: https://www.linkedin.com/in/mkowalczykiewicz
    icon: https://www.gravatar.com/avatar/47b4d7510e0f7738eb5c1612386b47d1
    organization: Infor (Poland) / University of Wroclaw
    contributes:
      - 
    speaker_experience:
      - Scalar 2018, ScalaUA 2019, InfoMEET 2019... More info with links please find on my webpage: http://www.ii.uni.wroc.pl/~kowalczykiewicz

  program:
    title: "バック・トゥ・ザ・フューチャー"
    length: 40 minutes
    language: English
    tags:
      - Big Data / Fast Data, Software Design and Architecture, Others
    keywords:
      - Logic Programming
Code Generators
Big Data
    detail: |
      論理プログラミングの始まりに戻ります。Prologと彼の新しいファミリーLogiQLについてお話しましょうモノリシックプログラミングモデルもブラッシュアップされ、ビッグデータ（LogicBlox）においては現代的な使用法も見られます。次に、述語をScalaと組み合わせてアプリケーションを作成する方法を示します。
```

- 英語の情報
```
- title: Back to the Future
- detail: We will go back to the beginnings of logic programming, discussing Prolog & his younger cousin (LogiQL). Monolithic programming model will also be brushed-up on & we will see its modern usage in Big Data (LogicBlox). We will then show how to combine predicates with Scala to generate applications.
```

- [ ] 和訳
- [ ] 日本語版の掲載

- 追加発表者の有無
```

```
  - [ ] Yesの場合には追加発表者を掲載する
