### ISSUE TITLE
[英語フォーム] CFPの掲載: Michal Kowalczykiewiczさんによる「Back to the Future」

### ISSUE THREAD

**Issue by tomoco95** [scalamatsuri/2020.scalamatsuri.org#260]
```
id: "" # proposalは人名-No
en:
  candidate:
    name: Michal Kowalczykiewicz
    twitter: 
    github: 
    other_sns: https://www.linkedin.com/in/mkowalczykiewicz
    icon: https://www.gravatar.com/avatar/47b4d7510e0f7738eb5c1612386b47d1
    organization: Infor (Poland) / University of Wroclaw
    contributes:
      - 
    speaker_experience:
      - Scalar 2018, ScalaUA 2019, InfoMEET 2019... More info with links please find on my webpage: http://www.ii.uni.wroc.pl/~kowalczykiewicz

  program:
    title: "Back to the Future"
    length: 40 minutes
    language: English
    tags:
      - Big Data / Fast Data, Software Design and Architecture, Others
    keywords:
      - Logic Programming
Code Generators
Big Data
    detail: |
      We will go back to the beginnings of logic programming, discussing Prolog & his younger cousin (LogiQL). Monolithic programming model will also be brushed-up on & we will see its modern usage in Big Data (LogicBlox). We will then show how to combine predicates with Scala to generate applications.
```

- [ ] 英語版の掲載

- 追加発表者の有無
```

```
- [ ] Yesの場合には追加発表者を掲載する
