### ISSUE TITLE
[日本語フォーム] CFPの掲載:  Taro L. Saitoさんによる「Scala無双: フロントエンドもバックエンドも全てScalaでなぎ倒せ」

### ISSUE THREAD

**Issue by tomoco95** [scalamatsuri/2020.scalamatsuri.org#261]
```
id: "" # proposalは人名-No
ja:
  candidate:
    name: "Taro L. Saito"
    twitter: taroleo
    github: xerial
    other_sns: 
    icon: https://pbs.twimg.com/profile_images/652040869705461760/eIm1fxaM_400x400.jpg
    organization: Arm Treasure Data
    contributes:
      - Airframe, sbt-sonatype, MessagePackなど
    speaker_experience:
     - - Scala Matsuri
- Conferenceなど
  program:
    title: "Scala無双: フロントエンドもバックエンドも全てScalaでなぎ倒せ"
    length: 40分
    language: Japanese
    tags:
      - Tools, Scalaビギナー（Scala歴1年くらいまで）, Microservices
    keywords:
      - Airframe Scala.js 
    detail: |
      Scalaは強力な言語で、Scala.jsによるWebブラウザ用のフロントエンドから、JVMで動くサーバーなど高性能なバックエンドプログラミングも可能です。このセッションでは、OSSであるAirframeフレームワークを用いて、アプリケーションを「全て」Scalaで作りきる手法を紹介します。
en:
  candidate:
    name: Taro L. Saito
    twitter: taroleo
    github: xerial
    other_sns: 
    icon: https://pbs.twimg.com/profile_images/652040869705461760/eIm1fxaM_400x400.jpg
    organization: Arm Treasure Data
    contributes:
      - Airframe, sbt-sonatype, MessagePackなど
    speaker_experience:
      - - Scala Matsuri
- Conferenceなど
  program:
    title: "Scala for Everything: From Frontend to Backend Applications"
    length: 40分
    language: Japanese
    tags:
      - Tools, Scalaビギナー（Scala歴1年くらいまで）, Microservices
    suggestions:
      - Airframe Scala.js 
    detail: |
      Scala is a powerful language; You can build frontend applications with Scala.js, and efficient backend application servers for JVM. In this session, we will learn how to build everything with Scala by using Airframe OSS framework. 
```

- [ ] 日本語版の掲載
- [ ] 英語版の掲載

- 追加発表者の有無
```
自分一人。自分の他に発表者はいない。
```
- [ ] 追加発表者がいる場合には掲載する
