### ISSUE TITLE
[英語フォーム] CFPの和訳と掲載: Jiri Jakes さんによる「Testing upside down」

### ISSUE THREAD

**Issue by tomoco95** [scalamatsuri/2020.scalamatsuri.org#262]
```
id: "" # proposalは人名-No
ja:
  candidate:
    name: "Jiri Jakes"
    twitter: 
    github: 
    other_sns: 
    icon: https://avatars3.githubusercontent.com/u/1381856
    organization: 
    contributes:
      - 
    speaker_experience:
      - • Multiple talks at Scala Taiwan Meetups (https://github.com/ScalaTaiwan/ScalaTaiwan/ marked by "Jiří Jakeš")
• Talk at JCConf (Java conference in Taipei; no recording)
• Unconference talk at Scala Matsuri 2019 ( https://www.youtube.com/watch?v=KG1XvPH-8rw )
  program:
    title: ""
    length: 40 minutes
    language: English
    tags:
      - Best Practices, Scala Beginners (~1year), Software Design and Architecture
    keywords:
      - testing
software design
    detail: |
      
```

- 英語の情報
```
- title: Testing upside down
- detail: You heard about testing of software. You have also written tests before. And you, most likely, have your own preferred style of writing tests. However, have you ever thought that your tests might not be exactly what you believe they are? In this talk, we will look at testing from different angle.
```

- [ ] 和訳
- [ ] 日本語版の掲載

- 追加発表者の有無
```

```
  - [ ] Yesの場合には追加発表者を掲載する
