### ISSUE TITLE
[英語フォーム] CFPの和訳と掲載: Jiri Jakes さんによる「The Phenomenon ZIO: Story of a new ecosystem」

### ISSUE THREAD

**Issue by tomoco95** [scalamatsuri/2020.scalamatsuri.org#264]
```
id: "" # proposalは人名-No
ja:
  candidate:
    name: "Jiri Jakes"
    twitter: 
    github: 
    other_sns: 
    icon: https://avatars3.githubusercontent.com/u/1381856
    organization: 
    contributes:
      - 
    speaker_experience:
      - • Multiple talks at Scala Taiwan Meetups  ( https://github.com/ScalaTaiwan/ScalaTaiwan/ marked by "Jiří Jakeš")
• Talk at JCConf (Java conference in Taipei; no recording)
• Unconference talk at Scala Matsuri 2019 ( https://www.youtube.com/watch?v=KG1XvPH-8rw )
  program:
    title: ""
    length: 40 minutes
    language: English
    tags:
      - Functional Programming, Tools
    keywords:
      - community
ZIO
    detail: |
      
```

- 英語の情報
```
- title: The Phenomenon ZIO: Story of a new ecosystem
- detail: ZIO is a Scala library for “type-safe, composable asynchronous and concurrent programming”. It seems that ZIO, and many related projects built on top of it, appeared out of blue sky, almost overnight. Let us have a look at origin and growth of this emerging Scala ecosystem.
```

- [ ] 和訳
- [ ] 日本語版の掲載

- 追加発表者の有無
```

```
  - [ ] Yesの場合には追加発表者を掲載する
