### ISSUE TITLE
[日本語フォーム] CFPの掲載:  谷口力斗 tanishikingさんによる「Metals: write Scala with your favorite text editor」

### ISSUE THREAD

**Issue by tomoco95** [scalamatsuri/2020.scalamatsuri.org#266]
```
id: "" # proposalは人名-No
ja:
  candidate:
    name: "谷口力斗 tanishiking"
    twitter: https://twitter.com/tanishiking25
    github: https://github.com/tanishiking
    other_sns: 
    icon: https://avatars0.githubusercontent.com/u/9353584?s=400&u=c3e5aba60a43901e7d2b7c0ea4caac06cde77049&v=4
    organization: 株式会社はてな
    contributes:
      - scalameta/scalafmt
scalameta/metals
    speaker_experience:
     - ScalaMatsuri 2019 https://speakerdeck.com/tanishiking/how-we-replaced-a-10-year-old-perl-product-using-scala
  program:
    title: "Metals: write Scala with your favorite text editor"
    length: 40分
    language: English
    tags:
      - Tools, Scalaビギナー（Scala歴1年くらいまで）
    keywords:
      - developer tool
IDE
metals
    detail: |
      2019年のJetbrains社の調査によると89%のScalaエンジニアは開発にIntelliJ IDEAを使っているそうです。
最近、ScalaのLSP実装であるMetalsの大きな進展によりvimやEmacsやVSCodeなど自分の好きなエディタからScalaを利用することが有力な選択肢となってきています。
この発表ではMetalsの主要な機能やアーキテクチャについてデモを交えてご紹介します。
en:
  candidate:
    name: Rikito Taniguchi
    twitter: https://twitter.com/tanishiking25
    github: https://github.com/tanishiking
    other_sns: 
    icon: https://avatars0.githubusercontent.com/u/9353584?s=400&u=c3e5aba60a43901e7d2b7c0ea4caac06cde77049&v=4
    organization: 株式会社はてな
    contributes:
      - scalameta/scalafmt
scalameta/metals
    speaker_experience:
      - ScalaMatsuri 2019 https://speakerdeck.com/tanishiking/how-we-replaced-a-10-year-old-perl-product-using-scala
  program:
    title: "Metals: write Scala with your favorite text editor"
    length: 40分
    language: English
    tags:
      - Tools, Scalaビギナー（Scala歴1年くらいまで）
    suggestions:
      - developer tool
IDE
metals
    detail: |
      According to the state of the developer ecosystem 2019, 89% of Scala developers use IntelliJ IDEA for their daily coding.
Thanks to the rise of Metals, an LSP implementation for Scala, it is a good option to write Scala in our favorite text editors such as Vim, Emacs, and VSCode.

In this talk, I present some brilliant features and architecture of Metals with some demos.
```

- [ ] 日本語版の掲載
- [ ] 英語版の掲載

- 追加発表者の有無
```
自分一人。自分の他に発表者はいない。
```
- [ ] 追加発表者がいる場合には掲載する
