### ISSUE TITLE
[英語フォーム] CFPの和訳と掲載: Douglas McPherson さんによる「A Guided Tour of The Amazing Akka Cluster」

### ISSUE THREAD

**Issue by tomoco95** [scalamatsuri/2020.scalamatsuri.org#267]
```
id: "" # proposalは人名-No
ja:
  candidate:
    name: "Douglas McPherson"
    twitter: 
    github: 
    other_sns: 
    icon: https://github.com/djm1329
    organization: Lightbend Inc.
    contributes:
      - 
    speaker_experience:
      - Reactive Summit 2017 (https://www.youtube.com/watch?v=TcG_sUNfWK8)
  program:
    title: ""
    length: 40 minutes
    language: English
    tags:
      - Tools, Scala Beginners (~1year), Software Design and Architecture
    keywords:
      - Akka
distributed computing
visualization 
    detail: |
      
```

- 英語の情報
```
- title: A Guided Tour of The Amazing Akka Cluster
- detail: Akka is a powerful toolkit implemented in Scala for concurrent and distributed computing. The Akka Cluster feature of Akka allows many compute nodes to be joined together in a group that acts as a single massive supercomputer. This talk uses visual simulations and live demos, with code examples in Scala, to provide a detailed tour of the workings of Akka Cluster and the amazing features it enables. The talk also describes several compelling use cases built with Akka Cluster. The attendee will come away with a deep and intuitive appreciation for the elegance and power of Akka Cluster.    
```

- [ ] 和訳
- [ ] 日本語版の掲載

- 追加発表者の有無
```

```
  - [ ] Yesの場合には追加発表者を掲載する
