### ISSUE TITLE
[英語フォーム] CFPの掲載: Douglas McPhersonさんによる「Forward Error Correction with Scala Cats and Akka Streams 」

### ISSUE THREAD

**Issue by tomoco95** [scalamatsuri/2020.scalamatsuri.org#272]
```
id: "" # proposalは人名-No
en:
  candidate:
    name: Douglas McPherson
    twitter: 
    github: 
    other_sns: 
    icon: https://github.com/djm1329
    organization: Lightbend Inc
    contributes:
      - 
    speaker_experience:
      - Reactive Summit 2017 (https://www.youtube.com/watch?v=TcG_sUNfWK8)
  program:
    title: "Forward Error Correction with Scala Cats and Akka Streams "
    length: 100 minutes (contains 20 minutes' break in all)
    language: English
    tags:
      - Functional Programming, Others
    keywords:
      - cats
akka streams
forward error correction
    detail: |
      Forward Error Correction (FEC) techniques have been studied since the 1950s and are ubiquitous in today's communication and storage systems. An introductory survey of the algebraic theory of linear FEC codes using examples written in Scala Cats is presented. A illustrative working simulation of a linear feedback shift register in Akka Streams is demonstrated, which in turn is used to implement a Reed-Solomon FEC code using the Cats toolkit. The talk will be of interest to people with a curiosity about how FEC works, an interest in Cats, or a desire to see a cool Akka Streams simulation.    
```

- [ ] 英語版の掲載

- 追加発表者の有無
```

```
- [ ] Yesの場合には追加発表者を掲載する
