### ISSUE TITLE
[日本語フォーム] CFPの掲載:  リチャード 伊真岡さんによる「Akka アクター、イベント・ソーシング、CQRS、クラスタリング・ハンズオン」

### ISSUE THREAD

**Issue by tomoco95** [scalamatsuri/2020.scalamatsuri.org#273]
```
id: "" # proposalは人名-No
ja:
  candidate:
    name: "リチャード 伊真岡"
    twitter: https://twitter.com/RichardImaokaJP
    github: https://github.com/richardimaoka
    other_sns: 
    icon: https://s.gravatar.com/avatar/14bfbc98a7d5ed3574be08f6b176ce70?s=80
    organization: マーベリック株式会社 技術広報
    contributes:
      - 
    speaker_experience:
     - Scala 関西 Summit 2019 https://speakerdeck.com/richardimaokajp/javafei-tong-qi-chu-li
builderscon 2018 https://builderscon.io/tokyo/2018/session/3b06e658-0386-4603-be45-798f77361b86
Fun Fun Functional (2) 関数型言語Lightning Talks!! https://speakerdeck.com/richardimaokajp/scala-ziowobatutichu-li-nishi-tutemita
  program:
    title: "Akka アクター、イベント・ソーシング、CQRS、クラスタリング・ハンズオン"
    length: 100分（合計20分の休憩を含む）
    language: Japanese
    tags:
      - Software Design and Architecture
    keywords:
      - Akka
CQRS
Clustering
    detail: |
      Akkaのアクター、イベント・ソーシング、CQRS、クラスタリングの機能を使ったハンズオンを行います。このセッションのゴールは参加者が自分でこれらの機能をもつAkkaアプリケーションをスクラッチから開発できることです。本番環境投入前のプロトタイプ作成などに役立つでしょう。サンプルのソースコードは完全な物をGitHub上で公開し、後から参加者が自分で触れるようにします。最初はごくシンプルなアプリケーションから、すこしずつ機能を追加し設計を変化させ、各段階で「どんな課題があるのか？」「新しい機能・設計を導入する理由は何なのか？」を説明します。
en:
  candidate:
    name: Richard Imaoka
    twitter: https://twitter.com/RichardImaokaJP
    github: https://github.com/richardimaoka
    other_sns: 
    icon: https://s.gravatar.com/avatar/14bfbc98a7d5ed3574be08f6b176ce70?s=80
    organization: マーベリック株式会社 技術広報
    contributes:
      - 
    speaker_experience:
      - Scala 関西 Summit 2019 https://speakerdeck.com/richardimaokajp/javafei-tong-qi-chu-li
builderscon 2018 https://builderscon.io/tokyo/2018/session/3b06e658-0386-4603-be45-798f77361b86
Fun Fun Functional (2) 関数型言語Lightning Talks!! https://speakerdeck.com/richardimaokajp/scala-ziowobatutichu-li-nishi-tutemita
  program:
    title: "Akka hands-on session - Actor, Event Sourcing, CQRS and Clustering"
    length: 100分（合計20分の休憩を含む）
    language: Japanese
    tags:
      - Software Design and Architecture
    suggestions:
      - Akka
CQRS
Clustering
    detail: |
      Learn about Akka's Actor, Event Sourcing, CQRS and Clustering. After the session, you will be able to create your own applications with these features from scratch. The full source code will be available on GitHub. We start from a simple application, make a change step by step and explain the background of each change.
```

- [ ] 日本語版の掲載
- [ ] 英語版の掲載

- 追加発表者の有無
```
自分一人。自分の他に発表者はいない。
```
- [ ] 追加発表者がいる場合には掲載する
