### ISSUE TITLE
[日本語フォーム] CFPの掲載:  前川 裕一さんによる「Clean ArchitectureとEffで変更に強いAPIを設計する」

### ISSUE THREAD

**Issue by tomoco95** [scalamatsuri/2020.scalamatsuri.org#275]
```
id: "" # proposalは人名-No
ja:
  candidate:
    name: "前川 裕一"
    twitter: https://twitter.com/_kaelaela
    github: https://github.com/kaelaela
    other_sns: 
    icon: https://twitter.com/_kaelaela/photo
    organization: アルプ株式会社
    contributes:
      - 
    speaker_experience:
     - DroidKaigi 2018, ScalaMatsuri 2019など
  program:
    title: "Clean ArchitectureとEffで変更に強いAPIを設計する"
    length: 40分
    language: Japanese
    tags:
      - Functional Programming, Software Design and Architecture
    keywords:
      - Clean Architecture / Eff / API Design
    detail: |
      APIのデザイン変更は、影響範囲がチーム内に閉じていれば共有&相談で破壊的な変更にも柔軟に対応できます。
しかし、外部に公開するAPIはそう簡単ではありません。
一度公開したモデルは簡単に変更できず、互換性の担保などの制約が生まれます。
プロダクトの急速な成長に対応しやすくするためにScalaとEff、Clean Architectureを使った変更に強いAPIデザインについて紹介します。
en:
  candidate:
    name: Yuichi Maekawa
    twitter: https://twitter.com/_kaelaela
    github: https://github.com/kaelaela
    other_sns: 
    icon: https://twitter.com/_kaelaela/photo
    organization: アルプ株式会社
    contributes:
      - 
    speaker_experience:
      - DroidKaigi 2018, ScalaMatsuri 2019など
  program:
    title: "A design of robust API using Eff and Clean Architecture in Scala"
    length: 40分
    language: Japanese
    tags:
      - Functional Programming, Software Design and Architecture
    suggestions:
      - Clean Architecture / Eff / API Design
    detail: |
      We may deal with breaking changes on API that affect only own team through communication efforts. But it's impossible at least for public API because we must consider backward compatibility etc. I'll introduce a robust API design using Eff and Clean Architecture to accompany fast-growing products.
```

- [ ] 日本語版の掲載
- [ ] 英語版の掲載

- 追加発表者の有無
```
自分一人。自分の他に発表者はいない。
```
- [ ] 追加発表者がいる場合には掲載する
