### ISSUE TITLE
[日本語フォーム] CFPの掲載:  竹尾 正馬 - @showmantさんによる「モジュラモノリスで表現する複雑なドメイン領域と境界」

### ISSUE THREAD

**Issue by tomoco95** [scalamatsuri/2020.scalamatsuri.org#276]
```
id: "" # proposalは人名-No
ja:
  candidate:
    name: "竹尾 正馬 - @showmant"
    twitter: showmant_
    github: showmant
    other_sns: 
    icon: https://avatars2.githubusercontent.com/u/5019215?s=460&v=4
    organization: アルプ株式会社 取締役
    contributes:
      - 
    speaker_experience:
     - Scala秋祭り
  program:
    title: "モジュラモノリスで表現する複雑なドメイン領域と境界"
    length: 40分
    language: Japanese
    tags:
      - Best Practices, Software Design and Architecture
    keywords:
      - modular monoliths
clean architecture
    detail: |
      アーキテクチャは組織成長、ドメイン、パフォーマンスの3つの要件を考慮して常に変化する必要があります。
しかしながら、スタートアップでマイクロサービスを導入するために、3つの要件全てを満たすには時間の制約や経験値から判断が困難なこともあります。
このセッションでは「モジュラモノリス」を採用するに至った経緯、Scalaでのコンテキスト境界の実現方法、サービス分断の痛みを軽減する工夫などを解説していきます。
en:
  candidate:
    name: Shoma Takeo - @showmant
    twitter: showmant_
    github: showmant
    other_sns: 
    icon: https://avatars2.githubusercontent.com/u/5019215?s=460&v=4
    organization: アルプ株式会社 取締役
    contributes:
      - 
    speaker_experience:
      - Scala秋祭り
  program:
    title: "Express complex domain regions and boundaries with 'modular monoliths'"
    length: 40分
    language: Japanese
    tags:
      - Best Practices, Software Design and Architecture
    suggestions:
      - modular monoliths
clean architecture
    detail: |
      The architecture must change constantly, considering three requirements: organizational growth, domain and performance.
However, to implement microservices at startup, it can be difficult to meet all the requirements.
We will explain how to realize context boundaries and reduce the pain of service division using "modular monolith" in Scala.
```

- [ ] 日本語版の掲載
- [ ] 英語版の掲載

- 追加発表者の有無
```
自分一人。自分の他に発表者はいない。
```
- [ ] 追加発表者がいる場合には掲載する
