### ISSUE TITLE
[日本語フォーム] CFPの掲載:  @omiendさんによる「如何にして刻々と変わるインターフェイスに対応すればよいのか」

### ISSUE THREAD

**Issue by tomoco95** [scalamatsuri/2020.scalamatsuri.org#277]
```
id: "" # proposalは人名-No
ja:
  candidate:
    name: "@omiend"
    twitter: https://twitter.com/omiend
    github: https://github.com/omiend
    other_sns: 
    icon: https://s.gravatar.com/avatar/93f52b85c90d3fc6afdfa7c61ce2a89e?s=80
    organization: アルプ株式会社
    contributes:
      - ScalaMatsuri
    speaker_experience:
     - 
  program:
    title: "如何にして刻々と変わるインターフェイスに対応すればよいのか"
    length: 40分
    language: Japanese
    tags:
      - Software Design and Architecture, Microservices, Others
    keywords:
      - API,Interface,ProtocolBuffer
    detail: |
      急成長するプロダクトが提供するAPIのインターフェイスは非常に変化が早く、連携するサブシステムの開発において常に"どのようにして変更を検知し、追従していくのか"という課題がつきまといます。 このセッションでは、日々刻々と変わるインターフェイスへ追従することの難しさと、如何にして対応したのかをお話します。
en:
  candidate:
    name: @omiend
    twitter: https://twitter.com/omiend
    github: https://github.com/omiend
    other_sns: 
    icon: https://s.gravatar.com/avatar/93f52b85c90d3fc6afdfa7c61ce2a89e?s=80
    organization: アルプ株式会社
    contributes:
      - ScalaMatsuri
    speaker_experience:
      - 
  program:
    title: "How to deal with the ever-changing interface"
    length: 40分
    language: Japanese
    tags:
      - Software Design and Architecture, Microservices, Others
    suggestions:
      - API,Interface,ProtocolBuffer
    detail: |
      The API interface provided by the rapidly growing products changes very quickly, and there is always the issue of "how to detect and follow changes" in the development of cooperating subsystems.
In this session, we will talk about the difficulty of following the ever-changing interface and how we responded.
```

- [ ] 日本語版の掲載
- [ ] 英語版の掲載

- 追加発表者の有無
```
自分一人。自分の他に発表者はいない。
```
- [ ] 追加発表者がいる場合には掲載する
