### ISSUE TITLE
[日本語フォーム] CFPの掲載:  門脇 拓巳 @blac_k_eyさんによる「Serverless Framework for Scala」

### ISSUE THREAD

**Issue by tomoco95** [scalamatsuri/2020.scalamatsuri.org#278]
```
id: "" # proposalは人名-No
ja:
  candidate:
    name: "門脇 拓巳 @blac_k_ey"
    twitter: https://twitter.com/blac_k_ey
    github: https://github.com/NomadBlacky
    other_sns: 
    icon: https://pbs.twimg.com/profile_images/1110501048559390720/UmgRho9s_400x400.jpg
    organization: 株式会社 セプテーニ・オリジナル エンジニア
    contributes:
      - https://github.com/serverless/serverless
https://github.com/NomadBlacky/scaladog
https://github.com/NomadBlacky/digdag-plugin-datadog
    speaker_experience:
     - Scala秋祭り 『面倒なことはScalaスクリプトにやらせよう』 https://speakerdeck.com/nomadblacky/let-scala-scripts-do-the-troublesome-things
Scala関西Summit 2018 『Readable Code in Scala』 https://gitpitch.com/NomadBlacky/slides/readable-code-in-scala#/
  program:
    title: "Serverless Framework for Scala"
    length: 40分
    language: Japanese
    tags:
      - Tools
    keywords:
      - Serverless Framework
AWS Lambda
    detail: |
      Serverless Frameworkはその名の通り、サーバレスアプリケーションの構成管理やデプロイを容易にするためののためのフレームワークです。
このセッションではAWSの環境を前提に、LambdaファンクションをScalaで実装する方法、アプリケーションのデプロイ、他のサービスとの連携、監視などを実例を交えて紹介します。
en:
  candidate:
    name: Takumi Kadowaki
    twitter: https://twitter.com/blac_k_ey
    github: https://github.com/NomadBlacky
    other_sns: 
    icon: https://pbs.twimg.com/profile_images/1110501048559390720/UmgRho9s_400x400.jpg
    organization: 株式会社 セプテーニ・オリジナル エンジニア
    contributes:
      - https://github.com/serverless/serverless
https://github.com/NomadBlacky/scaladog
https://github.com/NomadBlacky/digdag-plugin-datadog
    speaker_experience:
      - Scala秋祭り 『面倒なことはScalaスクリプトにやらせよう』 https://speakerdeck.com/nomadblacky/let-scala-scripts-do-the-troublesome-things
Scala関西Summit 2018 『Readable Code in Scala』 https://gitpitch.com/NomadBlacky/slides/readable-code-in-scala#/
  program:
    title: "Serverless Framework for Scala"
    length: 40分
    language: Japanese
    tags:
      - Tools
    suggestions:
      - Serverless Framework
AWS Lambda
    detail: |
      As the name suggests, Serverless Framework is a framework for facilitating configuration management and deployment of serverless applications.
In this session, introduce how to implement Lambda functions in Scala, deploy applications, cooperate with other services, monitoring, etc. with actual examples assuming the AWS environment.
```

- [ ] 日本語版の掲載
- [ ] 英語版の掲載

- 追加発表者の有無
```
自分一人。自分の他に発表者はいない。
```
- [ ] 追加発表者がいる場合には掲載する
