### ISSUE TITLE
[英語フォーム] CFPの和訳と掲載: Kamil Kloch さんによる「ZIO's take on error management, thread dumps and interruptions」

### ISSUE THREAD

**Issue by tomoco95** [scalamatsuri/2020.scalamatsuri.org#281]
```
id: "" # proposalは人名-No
ja:
  candidate:
    name: "Kamil Kloch"
    twitter: https://twitter.com/kamil_k
    github: https://github.com/kamilkloch
    other_sns: 
    icon: https://twitter.com/kamil_k
    organization: 
    contributes:
      - 
    speaker_experience:
      - 
  program:
    title: ""
    length: 40 minutes
    language: English
    tags:
      - Functional Programming, Tools, Others
    keywords:
      - zio
fibers
errors
    detail: |
      
```

- 英語の情報
```
- title: ZIO's take on error management, thread dumps and interruptions
- detail: Error management, error tracing, interruption - 3 complex topics in any concurrent application. We will describe the status quo from the standpoint of Scala's Future. Next, we will contrast it with unique features of ZIO: lossless errors, fiber dumps, execution traces, auto-supervision, programmable interruption. 

```

- [ ] 和訳
- [ ] 日本語版の掲載

- 追加発表者の有無
```

```
  - [ ] Yesの場合には追加発表者を掲載する
