### ISSUE TITLE
[英語フォーム] CFPの和訳と掲載: Kamil Kloch さんによる「Errors, diagnostics and interruptions with ZIO」

### ISSUE THREAD

**Issue by tomoco95** [scalamatsuri/2020.scalamatsuri.org#283]
```
id: "" # proposalは人名-No
ja:
  candidate:
    name: "Kamil Kloch"
    twitter: @kamil_k
    github: https://github.com/kamilkloch
    other_sns: 
    icon: https://avatars1.githubusercontent.com/u/807154?s=460&v=4
    organization: Software Engineer, Superfund Technologies
    contributes:
      - Minor contributions to zio and cats-mtl.
    speaker_experience:
      - No tech conference yet, a couple of academia talks in the past: http://kamilkloch.github.io/
  program:
    title: ""
    length: 40 minutes
    language: English
    tags:
      - Functional Programming, Best Practices
    keywords:
      - zio
fiber diagnostics
interruption
    detail: |
      
```

- 英語の情報
```
- title: Errors, diagnostics and interruptions with ZIO
- detail: Error management, error tracing, interruption - complex topics of a concurrent application. We will describe the status quo from the standpoint of Scala's Future. Next, we will contrast it with ZIO's take: lossless errors, fiber dumps, execution traces, auto-supervision, programmable interruption.
```

- [ ] 和訳
- [ ] 日本語版の掲載

- 追加発表者の有無
```

```
  - [ ] Yesの場合には追加発表者を掲載する
