### ISSUE TITLE
[日本語フォーム] CFPの掲載:  かず (@kazzna)さんによる「今から学ぶFree Monad」

### ISSUE THREAD

**Issue by tomoco95** [scalamatsuri/2020.scalamatsuri.org#285]
```
id: "" # proposalは人名-No
ja:
  candidate:
    name: "かず (@kazzna)"
    twitter: kazzna
    github: 
    other_sns: 
    icon: https://pbs.twimg.com/profile_images/577473638389055488/d0DD8ZJM.png
    organization: 
    contributes:
      - 
    speaker_experience:
     - 
  program:
    title: "今から学ぶFree Monad"
    length: 40分
    language: Japanese
    tags:
      - Functional Programming, Scalaビギナー（Scala歴1年くらいまで）
    keywords:
      - Begginners
Free Monad
    detail: |
      ScalazにFree Monadが導入された2011年以降、幾多のガチ勢による解説が行われてきました。
しかし、日本の現場ではまだまだ一般的に使われているとは言えない状況です。
このセッションでは正確さよりも概要を優先して、Freeの便利さや使いどころを説明します。
対象は`for 〜 yield`構文が書ける程度を想定しています。
en:
  candidate:
    name: Kazz (@kazzna)
    twitter: kazzna
    github: 
    other_sns: 
    icon: https://pbs.twimg.com/profile_images/577473638389055488/d0DD8ZJM.png
    organization: 
    contributes:
      - 
    speaker_experience:
      - 
  program:
    title: "Yet Another Free Monad Guide for Scala Beginners"
    length: 40分
    language: Japanese
    tags:
      - Functional Programming, Scalaビギナー（Scala歴1年くらいまで）
    suggestions:
      - Begginners
Free Monad
    detail: |
      Here in Japan, Free monad is still only used by expert functional professionals. 
This session will provide you general information about what it is and when to use.
```

- [ ] 日本語版の掲載
- [ ] 英語版の掲載

- 追加発表者の有無
```
自分一人。自分の他に発表者はいない。
```
- [ ] 追加発表者がいる場合には掲載する
