### ISSUE TITLE
[日本語フォーム] CFPの掲載:  集約のエンティティさんによる「イベントソーシングによるエンティティのバージョン管理設計」

### ISSUE THREAD

**Issue by tomoco95** [scalamatsuri/2020.scalamatsuri.org#286]
```
id: "" # proposalは人名-No
ja:
  candidate:
    name: "集約のエンティティ"
    twitter: pictiny
    github: pictiny
    other_sns: 
    icon: https://pbs.twimg.com/profile_images/1206924697796956162/cYvExC_4_400x400.jpg
    organization: アルプ株式会社
    contributes:
      - 
    speaker_experience:
     - builderscon 2019, ScalaMatsuri 2019 アンカンファレンスなど
https://speakerdeck.com/pictiny/shi-wozheng-sikuxi-utamefalsesisutemushe-ji
  program:
    title: "イベントソーシングによるエンティティのバージョン管理設計"
    length: 40分
    language: Japanese
    tags:
      - Best Practices, Software Design and Architecture
    keywords:
      - DDD
Domain Event
Event Sourcing
    detail: |
      エンティティの変更履歴はビジネスロジックを持つことがあります。
エンティティの状態や副作用を含めたバージョン管理はどの程度可能でしょうか？
時間軸を持った複雑なドメインオブジェクトのエンティティに対し、ドメインイベントをイベントソーシングすることでバージョン管理を実現できます。このようなバージョン管理の設計パターンを、Scalaの実装を例に紹介します。
en:
  candidate:
    name: Pictiny
    twitter: pictiny
    github: pictiny
    other_sns: 
    icon: https://pbs.twimg.com/profile_images/1206924697796956162/cYvExC_4_400x400.jpg
    organization: アルプ株式会社
    contributes:
      - 
    speaker_experience:
      - builderscon 2019, ScalaMatsuri 2019 アンカンファレンスなど
https://speakerdeck.com/pictiny/shi-wozheng-sikuxi-utamefalsesisutemushe-ji
  program:
    title: "Entity Versioning Pattern with Event Sourcing"
    length: 40分
    language: Japanese
    tags:
      - Best Practices, Software Design and Architecture
    suggestions:
      - DDD
Domain Event
Event Sourcing
    detail: |
      An entity's change history may have business logic.
How much entity versioning is possible, including state and side effects?
Domain Events and Event Sourcing can provide versioning for complex entities.
I will introduce the design pattern for entity versioning.
```

- [ ] 日本語版の掲載
- [ ] 英語版の掲載

- 追加発表者の有無
```
自分一人。自分の他に発表者はいない。
```
- [ ] 追加発表者がいる場合には掲載する
