### ISSUE TITLE
[日本語フォーム] CFPの掲載:  田所 駿佑さんによる「Scalaチームのオンボーディング」

### ISSUE THREAD

**Issue by tomoco95** [scalamatsuri/2020.scalamatsuri.org#287]
```
id: "" # proposalは人名-No
ja:
  candidate:
    name: "田所 駿佑"
    twitter: todokr
    github: todokr
    other_sns: 
    icon: https://avatars2.githubusercontent.com/u/2328540?s=460&v=4
    organization: 株式会社ビズリーチ
    contributes:
      - 
    speaker_experience:
     - ScalaMatsuri 2019 「Running Scala on AWS Lambda in a Snappy Way」 ( https://speakerdeck.com/todokr/running-scala-on-aws-lambda-in-a-snappy-way )
JJUG CCC 2017 Fall 「新しいプログラミング言語の学び方 HTTPサーバーを作って学ぶJava, Scala, Clojure」( https://speakerdeck.com/todokr/xin-siihurokuraminkuyan-yu-falsexue-hifang-httpsahawozuo-tutexue-hu-java-scala-clojure )
  program:
    title: "Scalaチームのオンボーディング"
    length: 40分
    language: Japanese
    tags:
      - Tools, Scalaビギナー（Scala歴1年くらいまで）, Others
    keywords:
      - knowledge sharing
employee experience
    detail: |
      Scalaの特色として挙げられるのが、柔軟性や抽象度の高いコードを記述できる表現力です。一方、それゆえにチームのコーディングスタイルへの新メンバーのキャッチアップが難しくなってしまうこともしばしばあります。
このセッションでは、新メンバーの入社前から業務の開始、活躍に至るまでの「オンボーディング」の取り組みや、活用しているツールを共有します。
en:
  candidate:
    name: Shunsuke Tadokoro
    twitter: todokr
    github: todokr
    other_sns: 
    icon: https://avatars2.githubusercontent.com/u/2328540?s=460&v=4
    organization: 株式会社ビズリーチ
    contributes:
      - 
    speaker_experience:
      - ScalaMatsuri 2019 「Running Scala on AWS Lambda in a Snappy Way」 ( https://speakerdeck.com/todokr/running-scala-on-aws-lambda-in-a-snappy-way )
JJUG CCC 2017 Fall 「新しいプログラミング言語の学び方 HTTPサーバーを作って学ぶJava, Scala, Clojure」( https://speakerdeck.com/todokr/xin-siihurokuraminkuyan-yu-falsexue-hifang-httpsahawozuo-tutexue-hu-java-scala-clojure )
  program:
    title: "Onboarding process of the Scala team"
    length: 40分
    language: Japanese
    tags:
      - Tools, Scalaビギナー（Scala歴1年くらいまで）, Others
    suggestions:
      - knowledge sharing
employee experience
    detail: |
      Scala is unique in its flexibility and expressiveness. On the other hand, such aspects sometimes make it hard for newcomer to catch up with the coding style of team.
In this session, I will share our Scala team's "Onboarding" process and tools to make teamwork work.
```

- [ ] 日本語版の掲載
- [ ] 英語版の掲載

- 追加発表者の有無
```
自分一人。自分の他に発表者はいない。
```
- [ ] 追加発表者がいる場合には掲載する
