### ISSUE TITLE
[日本語フォーム] CFPの掲載:  Eugene Yokota (eed3si9n)さんによる「自由、平等、ボックス化されたプリミティブ型」

### ISSUE THREAD

**Issue by tomoco95** [scalamatsuri/2020.scalamatsuri.org#288]
```
id: "" # proposalは人名-No
ja:
  candidate:
    name: "Eugene Yokota (eed3si9n)"
    twitter: eed3si9n_ja
    github: eed3si9n
    other_sns: 
    icon: https://secure.gravatar.com/avatar/8f41595db400be30176f6f04630c2842
    organization: Lightbend
    contributes:
      - sbt
Zinc
Scala
    speaker_experience:
     - Scala Days
Scala Sphere
nescala
  program:
    title: "自由、平等、ボックス化されたプリミティブ型"
    length: 40分
    language: Japanese
    tags:
      - Others
    keywords:
      - scala
equality
language design
    detail: |
      Scala における等価性に関して考察します。== は一見簡単そうに見えて実は複雑なトピックです。

Scala の言語仕様は等価性に関してあまり詳しく書いてありません。過去の議論などをさかのぼって == がどう振る舞うのかを考えてみましょう。
en:
  candidate:
    name: Eugene Yokota (eed3si9n)
    twitter: eed3si9n_ja
    github: eed3si9n
    other_sns: 
    icon: https://secure.gravatar.com/avatar/8f41595db400be30176f6f04630c2842
    organization: Lightbend
    contributes:
      - sbt
Zinc
Scala
    speaker_experience:
      - Scala Days
Scala Sphere
nescala
  program:
    title: "liberty, equality, and boxed primitive types"
    length: 40分
    language: Japanese
    tags:
      - Others
    suggestions:
      - scala
equality
language design
    detail: |
      In this talk, I will explore the equality in Scala. == is seemingly easy, but it's actually a complicated topic.

The Scala Language Spec doesn't explain much about equality. We'll try to revisit some of the past discussions and think how == actually behave.
```

- [ ] 日本語版の掲載
- [ ] 英語版の掲載

- 追加発表者の有無
```
自分一人。自分の他に発表者はいない。
```
- [ ] 追加発表者がいる場合には掲載する
