### ISSUE TITLE
[日本語フォーム] CFPの掲載:  Eugene Yokota (eed3si9n)さんによる「sbt 近況」

### ISSUE THREAD

**Issue by tomoco95** [scalamatsuri/2020.scalamatsuri.org#289]
```
id: "" # proposalは人名-No
ja:
  candidate:
    name: "Eugene Yokota (eed3si9n)"
    twitter: eed3si9n_ja
    github: eed3si9n
    other_sns: 
    icon: https://secure.gravatar.com/avatar/8f41595db400be30176f6f04630c2842
    organization: Lightbend
    contributes:
      - sbt
Zinc
Scala
    speaker_experience:
     - Scala Days
Scala Sphere
nescala
  program:
    title: "sbt 近況"
    length: 40分
    language: Japanese
    tags:
      - Tools
    keywords:
      - sbt
tooling
Zinc
    detail: |
      sbt とか Zinc で最近考えてることなど。
en:
  candidate:
    name: Eugene Yokota (eed3si9n)
    twitter: eed3si9n_ja
    github: eed3si9n
    other_sns: 
    icon: https://secure.gravatar.com/avatar/8f41595db400be30176f6f04630c2842
    organization: Lightbend
    contributes:
      - sbt
Zinc
Scala
    speaker_experience:
      - Scala Days
Scala Sphere
nescala
  program:
    title: "sbt status report"
    length: 40分
    language: Japanese
    tags:
      - Tools
    suggestions:
      - sbt
tooling
Zinc
    detail: |
      Updates around sbt and Zinc.
```

- [ ] 日本語版の掲載
- [ ] 英語版の掲載

- 追加発表者の有無
```
自分一人。自分の他に発表者はいない。
```
- [ ] 追加発表者がいる場合には掲載する
