### ISSUE TITLE
[英語フォーム] CFPの掲載: Thomas Suttonさんによる「Graphs with functional programming with free monads」

### ISSUE THREAD

**Issue by tomoco95** [scalamatsuri/2020.scalamatsuri.org#292]
```
id: "" # proposalは人名-No
en:
  candidate:
    name: Thomas Sutton
    twitter: 
    github: thsutton
    other_sns: 
    icon: https://media-exp1.licdn.com/dms/image/C5103AQHSJl23XHq9ZA/profile-displayphoto-shrink_200_200/0?e=1586390400&v=beta&t=3NRIM9xCLqCrhsVph05-8cvy6GkDmwrl73KwzhN_Spo
    organization: Simple Machines
    contributes:
      - aeson-diff - a Haskell implementation of JSON Patch
    speaker_experience:
      - Conferences: I presented a lightning talk at ScalaMatsuri 2019 https://m.youtube.com/watch?v=gs7MNm6YMX4 and at YOW! LambdaJam in Brisbane 2015
Meetups: I’ve presented at FP-Syd, Drupal WA, and other meetups several times.

Slides for some presentations can be found here: https://speakerdeck.com/thsutton
  program:
    title: "Graphs with functional programming with free monads"
    length: 40 minutes
    language: English
    tags:
      - Functional Programming
    keywords:
      - Data structures
Graphs
Free monads
    detail: |
      Algebraic data types represent tree-structured data very easily but graph-structured data can be more difficult due to “backward” edges. This talk describes one way to model graph-structured data in pure functional programming using ADTs and a structure very similar to the Free Monad.
```

- [ ] 英語版の掲載

- 追加発表者の有無
```

```
- [ ] Yesの場合には追加発表者を掲載する
