### ISSUE TITLE
[英語フォーム] CFPの和訳と掲載: Alexander Konovalov さんによる「Probabilistic Programming in Scala」

### ISSUE THREAD

**Issue by tomoco95** [scalamatsuri/2020.scalamatsuri.org#294]
```
id: "" # proposalは人名-No
ja:
  candidate:
    name: "Alexander Konovalov"
    twitter: https://twitter.com/alexknvl
    github: https://github.com/alexknvl
    other_sns: 
    icon: https://github.com/alexknvl
    organization: Compellon / Software Developer
    contributes:
      - 
    speaker_experience:
      - ScalaMatsuri 2019, LambdaConf 2019, LambdaConf 2018, https://github.com/cohomolo-gy/Isomorphic-Reasoning/blob/master/main.pdf https://slides.com/alexanderkonovalov-1/recursion-1/ https://www.youtube.com/watch?v=q_xPKaAcWtI&feature=emb_logo
  program:
    title: ""
    length: 100 minutes (contains 20 minutes' break in all)
    language: English
    tags:
      - Functional Programming, Tools, Data Science / Machine Learning
    keywords:
      - Probabilistic Programming
Applied Statistical Inference
Machine Learning
    detail: |
      
```

- 英語の情報
```
- title: Probabilistic Programming in Scala
- detail: Probabilistic programming is one of the easiest ways to do real statistical inference on real datasets. In this talk I will show you what you can do with PP, how to do that directly from Scala by interfacing with existing PP languages and how to implement your own ultra-simplified PP DSL in Scala.
```

- [ ] 和訳
- [ ] 日本語版の掲載

- 追加発表者の有無
```

```
  - [ ] Yesの場合には追加発表者を掲載する
