### ISSUE TITLE
[日本語フォーム] CFPの掲載:  鈴木 健一さんによる「Dotty ではじめるマルチステージプログラミング入門」

### ISSUE THREAD

**Issue by tomoco95** [scalamatsuri/2020.scalamatsuri.org#298]
```
id: "" # proposalは人名-No
ja:
  candidate:
    name: "鈴木 健一"
    twitter: 
    github: 
    other_sns: 
    icon: https://avatars2.githubusercontent.com/u/16099864?s=460&v=4
    organization: 
    contributes:
      - 
    speaker_experience:
     - Scala秋祭り (https://speakerdeck.com/dcubeio/from-tagless-final-to-typed-final-program-transformations-in-the-final-style)
  program:
    title: "Dotty ではじめるマルチステージプログラミング入門"
    length: 40分
    language: Japanese
    tags:
      - Functional Programming
    keywords:
      - Generative Programming
Abstraction without Regret
tagless-final
    detail: |
      マルチステージプログラミング (MSP) は、型安全な実行時コード生成と、オーバーヘッドのない抽象化を可能とするメタプログラミングの一種です。
Dotty (Scala 3) ではメタプログラミング機構が強化され、MSP が可能になりました。
このセッションでは、 MSP の概念やその基本的なプログラムの書き方、 さらに tagless-final と組み合わせた実用的で高性能なDSL構築アプローチについてお話します。
en:
  candidate:
    name: Kenichi Suzuki
    twitter: 
    github: 
    other_sns: 
    icon: https://avatars2.githubusercontent.com/u/16099864?s=460&v=4
    organization: 
    contributes:
      - 
    speaker_experience:
      - Scala秋祭り (https://speakerdeck.com/dcubeio/from-tagless-final-to-typed-final-program-transformations-in-the-final-style)
  program:
    title: "An introduction to multi-stage programming with Dotty"
    length: 40分
    language: Japanese
    tags:
      - Functional Programming
    suggestions:
      - Generative Programming
Abstraction without Regret
tagless-final
    detail: |
      Multi-stage programming (MSP) is a kind of meta-programming that enables type-safe runtime code generation and abstraction without regrets.
Dotty (Scala 3) has enhanced the meta-programming mechanism to allow MSP.
In this session, we will talk about the concept of MSP and how to write its program, and an approach combining MSP and tagless-final.
```

- [ ] 日本語版の掲載
- [ ] 英語版の掲載

- 追加発表者の有無
```
自分一人。自分の他に発表者はいない。
```
- [ ] 追加発表者がいる場合には掲載する
