### ISSUE TITLE
[日本語フォーム] CFPの掲載:  三浦勇さんによる「Scalaのための漸進的型付け」

### ISSUE THREAD

**Issue by tomoco95** [scalamatsuri/2020.scalamatsuri.org#299]
```
id: "" # proposalは人名-No
ja:
  candidate:
    name: "三浦勇"
    twitter: https://twitter.com/curelemonade2
    github: https://github.com/YuMuuu
    other_sns: 
    icon: https://twitter.com/curelemonade2/photo
    organization: 株式会社サイバーエージェント
    contributes:
      - Breeze
    speaker_experience:
     - 
  program:
    title: "Scalaのための漸進的型付け"
    length: 40分
    language: Japanese
    tags:
      - Functional Programming, Others
    keywords:
      - 
    detail: |
      Gradual Typingとはなにか．ScalaはGradual Typingの定理を満たしているのか．またScalaでGradual Typingを満たすにはどうすれば良いかを解説します
en:
  candidate:
    name: Yu Miura
    twitter: https://twitter.com/curelemonade2
    github: https://github.com/YuMuuu
    other_sns: 
    icon: https://twitter.com/curelemonade2/photo
    organization: 株式会社サイバーエージェント
    contributes:
      - Breeze
    speaker_experience:
      - 
  program:
    title: "Gradual Typing for Scala"
    length: 40分
    language: Japanese
    tags:
      - Functional Programming, Others
    suggestions:
      - 
    detail: |
      What is Gradual Typing? Does Scala satisfy Gradual Typing's theorem? In addition, we will explain how to satisfy Gradual Typing in Scala.
```

- [ ] 日本語版の掲載
- [ ] 英語版の掲載

- 追加発表者の有無
```
自分一人。自分の他に発表者はいない。
```
- [ ] 追加発表者がいる場合には掲載する
