### ISSUE TITLE
[英語フォーム] CFPの和訳と掲載: Alexander Konovalov さんによる「Thinking about Mutability with Affine Types in Scala」

### ISSUE THREAD

**Issue by tomoco95** [scalamatsuri/2020.scalamatsuri.org#300]
```
id: "" # proposalは人名-No
ja:
  candidate:
    name: "Alexander Konovalov"
    twitter: https://twitter.com/alexknvl
    github: https://github.com/alexknvl
    other_sns: 
    icon: https://github.com/alexknvl
    organization: Compellon / Software Developer
    contributes:
      - 
    speaker_experience:
      - ScalaMatsuri 2019, LambdaConf 2019, LambdaConf 2018, https://twitter.com/alexknvl/status/1148978882281955328, https://www.youtube.com/watch?v=q_xPKaAcWtI&feature=emb_logo
  program:
    title: ""
    length: 40 minutes
    language: English
    tags:
      - Functional Programming
    keywords:
      - Substructural Type Systems
Affine Types
    detail: |
      
```

- 英語の情報
```
- title: Thinking about Mutability with Affine Types in Scala
- detail: While Scala 2/3 does not support affine types (or other substructural types), they are still useful conceptually to think about limited-scope mutability. Is passing StringBuilder around a pure FP heresy, or is there a justification and an intuition for it through substructural type systems?
```

- [ ] 和訳
- [ ] 日本語版の掲載

- 追加発表者の有無
```

```
  - [ ] Yesの場合には追加発表者を掲載する
