### ISSUE TITLE
[英語フォーム] CFPの掲載: Alexander Konovalovさんによる「Thinking about Mutability with Affine Types in Scala」

### ISSUE THREAD

**Issue by tomoco95** [scalamatsuri/2020.scalamatsuri.org#301]
```
id: "" # proposalは人名-No
en:
  candidate:
    name: Alexander Konovalov
    twitter: https://twitter.com/alexknvl
    github: https://github.com/alexknvl
    other_sns: 
    icon: https://github.com/alexknvl
    organization: Compellon / Software Developer
    contributes:
      - 
    speaker_experience:
      - ScalaMatsuri 2019, LambdaConf 2019, LambdaConf 2018, https://twitter.com/alexknvl/status/1148978882281955328, https://www.youtube.com/watch?v=q_xPKaAcWtI&feature=emb_logo
  program:
    title: "Thinking about Mutability with Affine Types in Scala"
    length: 40 minutes
    language: English
    tags:
      - Functional Programming
    keywords:
      - Substructural Type Systems
Affine Types
    detail: |
      While Scala 2/3 does not support affine types (or other substructural types), they are still useful conceptually to think about limited-scope mutability. Is passing StringBuilder around a pure FP heresy, or is there a justification and an intuition for it through substructural type systems?
```

- [ ] 英語版の掲載

- 追加発表者の有無
```

```
- [ ] Yesの場合には追加発表者を掲載する
