### ISSUE TITLE
[日本語フォーム] CFPの掲載:  藪本晃輔さんによる「Akka Streams vs Spark Structured  Streaming」

### ISSUE THREAD

**Issue by tomoco95** [scalamatsuri/2020.scalamatsuri.org#302]
```
id: "" # proposalは人名-No
ja:
  candidate:
    name: "藪本晃輔"
    twitter: @yabooun
    github: https://github.com/glyabumoto
    other_sns: Facebook: https://www.facebook.com/kousuke.yabumoto.9
    icon: https://gyazo.com/ff39803a571de190ae02c85267540d8b
    organization: 株式会社ジオロジック CTO
    contributes:
      - 
    speaker_experience:
     - #6 市ヶ谷Geek★Night「アドテク百花繚乱」
https://ichigayageek.connpass.com/event/27420/
  program:
    title: "Akka Streams vs Spark Structured  Streaming"
    length: 40分
    language: Japanese
    tags:
      - Big Data / Fast Data, Software Design and Architecture
    keywords:
      - Akka Streams
Spark
Structured  Streaming
    detail: |
      大量データへのストリーミング処理の実装方法として、Akka StreamsとSpark Structured Streamingがあります。

では、実案件ではどちらを採用すべきでしょうか。
仕様の表現力、信頼性、即応性、弾力性、耐障害性などはどうでしょうか。

この２つについて概要および簡単な使い方を説明し、気になる部分を比較して、課題をクリアするテクニックを紹介します。
en:
  candidate:
    name: Kosuke Yabumoto
    twitter: @yabooun
    github: https://github.com/glyabumoto
    other_sns: Facebook: https://www.facebook.com/kousuke.yabumoto.9
    icon: https://gyazo.com/ff39803a571de190ae02c85267540d8b
    organization: 株式会社ジオロジック CTO
    contributes:
      - 
    speaker_experience:
      - #6 市ヶ谷Geek★Night「アドテク百花繚乱」
https://ichigayageek.connpass.com/event/27420/
  program:
    title: "Akka Streams vs Spark Structured  Streaming"
    length: 40分
    language: Japanese
    tags:
      - Big Data / Fast Data, Software Design and Architecture
    suggestions:
      - Akka Streams
Spark
Structured  Streaming
    detail: |
      Akka Streams and Spark Structured Streaming are way to implement streaming for big data.
So, which is better?
How about the power of expression, reliable, responsive, elastic, resilient.
I'll explain the overview and compare these worrisome parts and introduce techniques for clearing the issues.
```

- [ ] 日本語版の掲載
- [ ] 英語版の掲載

- 追加発表者の有無
```
自分一人。自分の他に発表者はいない。
```
- [ ] 追加発表者がいる場合には掲載する
