### ISSUE TITLE
[日本語フォーム] CFPの掲載:  谷口 慶一郎さんによる「Scalaで圏論の世界をのぞいてみる」

### ISSUE THREAD

**Issue by tomoco95** [scalamatsuri/2020.scalamatsuri.org#303]
```
id: "" # proposalは人名-No
ja:
  candidate:
    name: "谷口 慶一郎"
    twitter: @ravineport
    github: taniTk
    other_sns: 
    icon: https://www.facebook.com/photo.php?fbid=1645682899037203&set=pb.100007865262817.-2207520000..&type=3&theater
    organization: Fringe 81株式会社 エンジニア
    contributes:
      - 
    speaker_experience:
     - Scala関西Summit 2019
https://speakerdeck.com/tanitk/scaladequan-lun-tiyotutoxue-bu
  program:
    title: "Scalaで圏論の世界をのぞいてみる"
    length: 40分
    language: Japanese
    tags:
      - Functional Programming, Others
    keywords:
      - Category Theory
Monad
    detail: |
      関数型プログラミングを学んでいると出会う圏論の世界。
関数型ライブラリを見ていてもFunctorやMonadなどなど圏論由来の言葉が多くでてきます。
本セッションでは、圏論の基礎を学ぶとともに様々な概念がScalaでどういった表現になるのかを紹介します。
Scala関西 2019の発表と内容がかぶる部分があります。
en:
  candidate:
    name: Taniguchi Keiichiro
    twitter: @ravineport
    github: taniTk
    other_sns: 
    icon: https://www.facebook.com/photo.php?fbid=1645682899037203&set=pb.100007865262817.-2207520000..&type=3&theater
    organization: Fringe 81株式会社 エンジニア
    contributes:
      - 
    speaker_experience:
      - Scala関西Summit 2019
https://speakerdeck.com/tanitk/scaladequan-lun-tiyotutoxue-bu
  program:
    title: "Looking at category theory thorough Scala"
    length: 40分
    language: Japanese
    tags:
      - Functional Programming, Others
    suggestions:
      - Category Theory
Monad
    detail: |
      We meet category theory learning functional programming.
Many words from category theory like Functor, Monad, etc appear in functional libraries.
This session introduce the basics of category theory and the representations of these concepts in Scala.
```

- [ ] 日本語版の掲載
- [ ] 英語版の掲載

- 追加発表者の有無
```
自分一人。自分の他に発表者はいない。
```
- [ ] 追加発表者がいる場合には掲載する
