### ISSUE TITLE
[日本語フォーム] CFPの掲載:  丹賀 健一さんによる「PofEAAで読み解くSaaSバックエンドの現場のコード」

### ISSUE THREAD

**Issue by tomoco95** [scalamatsuri/2020.scalamatsuri.org#304]
```
id: "" # proposalは人名-No
ja:
  candidate:
    name: "丹賀 健一"
    twitter: dnskimox
    github: dnskimo
    other_sns: 
    icon: https://twitter.com/dnskimox/photo
    organization: アルプ株式会社 エンジニア
    contributes:
      - 
    speaker_experience:
     - PHPカンファレンス福岡2018
PHPカンファレンス仙台2019
  program:
    title: "PofEAAで読み解くSaaSバックエンドの現場のコード"
    length: 40分
    language: Japanese
    tags:
      - Best Practices, Scalaビギナー（Scala歴1年くらいまで）, Software Design and Architecture
    keywords:
      - OOP
RDB
PofEAA
    detail: |
      SaaSの開発現場では複雑なビジネスモデルをコードに落とし込むため、地に足のついた設計技能が不可欠です。そんな時、Martin Fowler氏の著した『Patterns of Enterprise Application Architecture』は、時代を経た今でも十分有力な情報源になります。このセッションでは、Scalaの多彩な表現力を用いてPofEAAのパターンを実装した実例をご紹介します。
en:
  candidate:
    name: Kenichi Tanga
    twitter: dnskimox
    github: dnskimo
    other_sns: 
    icon: https://twitter.com/dnskimox/photo
    organization: アルプ株式会社 エンジニア
    contributes:
      - 
    speaker_experience:
      - PHPカンファレンス福岡2018
PHPカンファレンス仙台2019
  program:
    title: "Reading code of SaaS backend, guided by PofEAA"
    length: 40分
    language: Japanese
    tags:
      - Best Practices, Scalaビギナー（Scala歴1年くらいまで）, Software Design and Architecture
    suggestions:
      - OOP
RDB
PofEAA
    detail: |
      On SaaS development scenes, mature design skill is required to make code refrect complex business models.In that situation, Martin Fowler's "Patterns of Enterprise Application Architecture" is still a powerful source of idea even after the times.In this session, I will introduce examples of implementing PofEAA using Scala's expressive powers.
```

- [ ] 日本語版の掲載
- [ ] 英語版の掲載

- 追加発表者の有無
```
自分一人。自分の他に発表者はいない。
```
- [ ] 追加発表者がいる場合には掲載する
