### ISSUE TITLE
[英語フォーム] CFPの和訳と掲載: Sahil Sawhney さんによる「Operating your infrastructure with Scala based Hubots」

### ISSUE THREAD

**Issue by tomoco95** [scalamatsuri/2020.scalamatsuri.org#306]
```
id: "" # proposalは人名-No
ja:
  candidate:
    name: "Sahil Sawhney"
    twitter: https://twitter.com/lihas5
    github: 
    other_sns: 
    icon: https://pbs.twimg.com/profile_images/1091401167706488832/ZKQS9pXS_400x400.jpg
    organization: Lead Consultant, Knoldus Software
    contributes:
      - 
    speaker_experience:
      - Scala Matsuri 2019 -> https://www.youtube.com/watch?v=-31YjUKQcq4
Tech triveni 2018 -> https://www.youtube.com/watch?v=_mVmxosuK1c
Meetups and Other community sessions.
  program:
    title: ""
    length: 40 minutes
    language: English
    tags:
      - Tools, DevOps, Software Design and Architecture, Others
    keywords:
      - Hubot
Scala
DevOps
    detail: |
      
```

- 英語の情報
```
- title: Operating your infrastructure with Scala based Hubots
- detail: A standard microservice architecture includes components like microservice, Kafka, Cassandra, Elasticsearch, etc and these components could be behind a proxy. In this session, we will see how one can provide the first aid to these components securely in case anything goes down with Scala based Hubot
```

- [ ] 和訳
- [ ] 日本語版の掲載

- 追加発表者の有無
```

```
  - [ ] Yesの場合には追加発表者を掲載する
