### ISSUE TITLE
[日本語フォーム] CFPの掲載:  湯上 尚哉さんによる「Scalaで書かれたAndroidアプリをKotlinで書き直した話」

### ISSUE THREAD

**Issue by tomoco95** [scalamatsuri/2020.scalamatsuri.org#308]
```
id: "" # proposalは人名-No
ja:
  candidate:
    name: "湯上 尚哉"
    twitter: 
    github: 
    other_sns: 
    icon: https://avatars0.githubusercontent.com/u/11360473?s=400&u=980bfa0c895732d683c68f6529b195d9e2993864&v=4
    organization: 株式会社セプテーニ・オリジナル
    contributes:
      - 
    speaker_experience:
     - 
  program:
    title: "Scalaで書かれたAndroidアプリをKotlinで書き直した話"
    length: 40分
    language: Japanese
    tags:
      - Scalaビギナー（Scala歴1年くらいまで）, Others
    keywords:
      - Android
Kotlin
refactoring
    detail: |
      GANMA!は2013年にサービスを開始した漫画配信サービスで、バックエンドはほぼ全てScalaで実装されおり、Androidアプリもほぼ全てScalaで実装されていました。しかしここ数年の情勢から既存のコードをKotlinで書き換えるプロジェクトが開始されました。このセッションではScalaで書かれたコードをKotlinに置き換える上で得られた知見を紹介します。
en:
  candidate:
    name: Yunoue Naoya
    twitter: 
    github: 
    other_sns: 
    icon: https://avatars0.githubusercontent.com/u/11360473?s=400&u=980bfa0c895732d683c68f6529b195d9e2993864&v=4
    organization: 株式会社セプテーニ・オリジナル
    contributes:
      - 
    speaker_experience:
      - 
  program:
    title: "The story of rewriting Android application written in Scala with Kotlin"
    length: 40分
    language: Japanese
    tags:
      - Scalaビギナー（Scala歴1年くらいまで）, Others
    suggestions:
      - Android
Kotlin
refactoring
    detail: |
      GANMA! is an original manga distribution service that implemented in Scala, and Android application was also Scala (of cause!). However, recent circumstances have led to a project to rewriting with Kotlin. In this session, we will introduce the knowledge gained from replacing Scala to Kotlin.
```

- [ ] 日本語版の掲載
- [ ] 英語版の掲載

- 追加発表者の有無
```
自分の他にも追加の発表者がいる。
```
- [ ] 追加発表者がいる場合には掲載する
