### ISSUE TITLE
[英語フォーム] CFPの掲載: Jakub Kozłowskiさんによる「Write yourself a CLI tool - no more bash」

### ISSUE THREAD

**Issue by tomoco95** [scalamatsuri/2020.scalamatsuri.org#310]
```
id: "" # proposalは人名-No
en:
  candidate:
    name: Jakub Kozłowski
    twitter: kubukoz
    github: kubukoz
    other_sns: 
    icon: https://blog.kubukoz.com/assets/images/kubukoz.jpg
    organization: 
    contributes:
      - I help maintain fs2 and redis4cats, and I sometimes contribute to cats-effect.
    speaker_experience:
      - I spoke at Scala Italy, Scalar and flatMap(Oslo).

Videos:

https://vimeo.com/368027707

https://www.youtube.com/watch?v=fZO2lV2xjEo

https://www.youtube.com/watch?v=HMs_F7LXTak
  program:
    title: "Write yourself a CLI tool - no more bash"
    length: 40 minutes
    language: English
    tags:
      - Functional Programming, Tools, Best Practices, Software Design and Architecture
    keywords:
      - tools
functional programming
command line
    detail: |
      Ever wished you had utilities for day-to-day tasks in the shell, but didn't want to write bash scripts?
Having problems learning the syntax of sed and awk? This talk is for you - learn how to structure a command line application in the language you know, which tools to use to build it, and how to make it run faster.
```

- [ ] 英語版の掲載

- 追加発表者の有無
```

```
- [ ] Yesの場合には追加発表者を掲載する
