### ISSUE TITLE
[英語フォーム] CFPの掲載: Jakub Kozłowskiさんによる「Domain Specific Languages in the real world for beginners」

### ISSUE THREAD

**Issue by tomoco95** [scalamatsuri/2020.scalamatsuri.org#312]
```
id: "" # proposalは人名-No
en:
  candidate:
    name: Jakub Kozłowski
    twitter: kubukoz
    github: kubukoz
    other_sns: 
    icon: https://blog.kubukoz.com/assets/images/kubukoz.jpg
    organization: 
    contributes:
      - I help maintain fs2 and redis4cats, and I sometimes contribute to cats-effect.
    speaker_experience:
      - I spoke at Scala Italy, Scalar and flatMap(Oslo).

Videos:

https://vimeo.com/368027707

https://www.youtube.com/watch?v=fZO2lV2xjEo

https://www.youtube.com/watch?v=HMs_F7LXTak
  program:
    title: "Domain Specific Languages in the real world for beginners"
    length: 40 minutes
    language: English
    tags:
      - Functional Programming, Best Practices, Scala Beginners (~1year), Software Design and Architecture
    keywords:
      - 
    detail: |
      One of the reasons Scala is praised for is the ability to write concise DSLs in it.
However, that power is often underappreciated and most people don't write any.
Learn what situations Domain Specific Languages can help you with, what makes a good one, and how they can be implemented.
```

- [ ] 英語版の掲載

- 追加発表者の有無
```

```
- [ ] Yesの場合には追加発表者を掲載する
