### ISSUE TITLE
[英語フォーム] CFPの和訳と掲載: Tamer Abdulradi さんによる「 Designing Recursive Data Types」

### ISSUE THREAD

**Issue by tomoco95** [scalamatsuri/2020.scalamatsuri.org#314]
```
id: "" # proposalは人名-No
ja:
  candidate:
    name: "Tamer Abdulradi"
    twitter: tabdulradi
    github: tabdulradi
    other_sns: https://www.linkedin.com/in/tamerradi/
    icon: https://pbs.twimg.com/profile_images/897100228947570688/6-b3f3gs_400x400.jpg
    organization: Just Eat
    contributes:
      - scala https://github.com/scala/scala/pulls?q=is%3Apr+is%3Aclosed+author%3Atabdulradi
atto https://github.com/tpolecat/atto/pull/79
nullable https://github.com/tabdulradi/nullable
    speaker_experience:
      - Scala World https://www.youtube.com/watch?v=dbqRqhHpggs
Scala Exchange (All vids are gone, but check twitter feedback like: https://twitter.com/ValentinKasas/status/1073199213956292609)
Scala Days https://www.youtube.com/watch?v=OedtxbyexaY
  program:
    title: ""
    length: 40 minutes
    language: English
    tags:
      - Functional Programming, Best Practices, Scala Beginners (~1year), Software Design and Architecture
    keywords:
      - Recursion Schemes
ADT
    detail: |
      
```

- 英語の情報
```
- title:  Designing Recursive Data Types
- detail: How to model your own recursive data type and how this affects it’s the way you write code to traverse or manipulate it. Comparing 3 approaches: good old Recursion, Visitor Pattern and Recursion schemes using animations to explain how they work.
```

- [ ] 和訳
- [ ] 日本語版の掲載

- 追加発表者の有無
```

```
  - [ ] Yesの場合には追加発表者を掲載する
