### ISSUE TITLE
[英語フォーム] CFPの和訳と掲載: Harry Laoulakos さんによる「Algebras in Programming」

### ISSUE THREAD

**Issue by tomoco95** [scalamatsuri/2020.scalamatsuri.org#45]
```
id: "" # proposalは人名-No
ja:
  candidate:
    name: "Harry Laoulakos"
    twitter: https://twitter.com/harrylaou
    github: https://github.com/harrylaou
    other_sns: https://www.linkedin.com/in/harrylaou/
    icon: https://www.dropbox.com/s/t6ufl9iyvrdpep0/harry.jpg?dl=0
    organization: Talos Software
    contributes:
      - 
    speaker_experience:
      - "Shapeless 101"
- https://scala.io/2016/speakers.html#/b3e01a349f1eb483384fcb27102073b9aa62861e
- https://harrylaou.com/slides/shapeless101.pdf
- No Video available 

-"Monad Stacks or: How I Learned to Stop Worrying and Love the Free Monad"
- I gave this talk in TypeLevel Summit, and  and have been asked to give it in more conferences 
- Code : https://gitlab.com/harrylaou/monad-stacks
- Slides : https://harrylaou.com/slides/MonadStacks.pdf
- video: https://www.youtube.com/watch?v=2TDDDFGa8-0

  program:
    title: ""
    length: 40 minutes
    language: English
    tags:
      - Functional Programming, Scala Beginners (~1year)
    keywords:
      - Functional Programming
Algebra 
ADT
    detail: |
      
```

- 英語の情報
```
- title: Algebras in Programming
- detail: Tuples, case classes and sealed traits are common data structures in Scala. Sometimes called products and co-products, they define algebraic data types. They are called ADTs in abbreviation. But where is the algebra in them?
The correspondence of data structures that we use every day in Scala with “regular” is not obvious at first sight.
Also, the term algebra is used in different concepts, like free monads, tagless final interpreters and recursion schemes. After watching this talk the use of this ambiguous term will be clarified.
No previous scala knowledge required. 
```

- [ ] 和訳
- [ ] 日本語版の掲載

- 追加発表者の有無
```

```
  - [ ] Yesの場合には追加発表者を掲載する
