### ISSUE TITLE
[日本語フォーム] CFPの掲載:  giiitaさんによる「DDD optimized framework Scaladia」

### ISSUE THREAD

**Issue by tomoco95** [scalamatsuri/2020.scalamatsuri.org#48]
```
id: "" # proposalは人名-No
ja:
  candidate:
    name: "giiita"
    twitter: @omarun_4263
    github: https://github.com/giiita
    other_sns: 
    icon: https://github.com/giiita
    organization: 株式会社セプテーニ・オリジナル ソフトウェアエンジニア
    contributes:
      - scaladia
sbt-protoc
    speaker_experience:
     - 2019Scala秋祭り
  program:
    title: "DDD optimized framework Scaladia"
    length: 40分
    language: Japanese
    tags:
      - Software Design and Architecture
    keywords:
      - Dependency Injection
Architecture design
DDD
    detail: |
      レイヤードアーキテクチャにおけるDependency Injectionをベースとしたフレームワーク、Scaladiaの紹介をします。
柔軟で高速、かつ、Scalaならではの表現力を十分に発揮することができます。
en:
  candidate:
    name: giiita
    twitter: @omarun_4263
    github: https://github.com/giiita
    other_sns: 
    icon: https://github.com/giiita
    organization: 株式会社セプテーニ・オリジナル ソフトウェアエンジニア
    contributes:
      - scaladia
sbt-protoc
    speaker_experience:
      - 2019Scala秋祭り
  program:
    title: "DDD optimized framework Scaladia"
    length: 40分
    language: Japanese
    tags:
      - Software Design and Architecture
    keywords:
      - Dependency Injection
Architecture design
DDD
    detail: |
      Introducing Scaladia, a framework based on Dependency Injection in layered architecture.
It is flexible and fast, and can fully demonstrate the expressive power of Scala.
```

- [ ] 日本語版の掲載
- [ ] 英語版の掲載

- 追加発表者の有無
```
自分一人。自分の他に発表者はいない。
```
- [ ] 追加発表者がいる場合には掲載する
