### ISSUE TITLE
[日本語フォーム] CFPの掲載:  高橋 知子(公開される氏名)さんによる「(テストデータ)バックオフィスでScala使ってみた」

### ISSUE THREAD

**Issue by tomoco95** [scalamatsuri/2020.scalamatsuri.org#5]
```
id: "" # proposalは人名-No
ja:
  candidate:
    name: "高橋 知子(公開される氏名)"
    twitter: scalamatsuri
    github: tomoco95
    icon: https://twitter.com/scalamatsuri
    organization: JSA バックオフィスチーム
    contributes:
      - - OSS1
- OSS2
- OSS3
    speaker_experience:
     - - ScalaMatsuri2017
- ScalaMatsuri2018
- ScalaMatsuri2019
  program:
    title: "(テストデータ)バックオフィスでScala使ってみた"
    length: 40分
    language: Japanese
    tags:
      - Big Data / Fast Data, Tools, Scalaビギナー（Scala歴1年くらいまで）
    suggestions:
      - backoffice
keyword
english only
    detail: |
      バックオフィスでScala使ってみた話をします。(すみません、テストデータです。)
en:
  candidate:
    name: Tomoko Takahashi
    twitter: scalamatsuri
    github: tomoco95
    icon: https://twitter.com/scalamatsuri
    organization: JSA バックオフィスチーム
    contributes:
      - - OSS1
- OSS2
- OSS3
    speaker_experience:
      - - ScalaMatsuri2017
- ScalaMatsuri2018
- ScalaMatsuri2019
  program:
    title: "(test)バックオフィスでScala使ってみた(実際には英語タイトルが入ります)"
    length: 40分
    language: Japanese
    tags:
      - Big Data / Fast Data, Tools, Scalaビギナー（Scala歴1年くらいまで）
    suggestions:
      - backoffice
keyword
english only
    detail: |
      (実際には英語のセッション概要が入ります)バックオフィスでScala使ってみた話をします。(すみません、テストデータです。)
```

- [ ] 日本語版の掲載
- [ ] 英語版の掲載
