### ISSUE TITLE
[英語フォーム] CFPの和訳と掲載: Vitaly Bragilevsky さんによる「DOT for kiddies」

### ISSUE THREAD

**Issue by tomoco95** [scalamatsuri/2020.scalamatsuri.org#55]
```
id: "" # proposalは人名-No
ja:
  candidate:
    name: "Vitaly Bragilevsky"
    twitter: VBragilevsky
    github: bravit
    other_sns: 
    icon: https://avatars2.githubusercontent.com/u/298521?s=400&u=f2bf3cc53dfd445bcdefae3a39ebbfa7a2b72c55&v=4
    organization: Lecturer at JetBrains
    contributes:
      - I contributed to the Glasgow Haskell Compiler (I'm the member of GHC Steering Committee)
    speaker_experience:
      - All my talks are available at https://www.youtube.com/user/bravit111, including:
1) LambdaConf 2018 (set of lectures, slides& other materials: https://github.com/bravit/tt-ghc-exercises, video: https://www.youtube.com/playlist?list=PLvPsfYrGz3wspkm6LVEjndvQqK6SkcXaT)
2) F(By) 2019 (https://www.youtube.com/watch?v=8YGtMrQ5keA)
3) BOBKonf 2019 (Berlin, https://github.com/bravit/bob19-tutorial-types, no video recording)

  program:
    title: "こどものためのDOT"
    length: 100 minutes (contains 20 minutes' break in all)
    language: English
    tags:
      - Functional Programming, Others
    keywords:
      - theory
dependent objects
foundations
    detail: |
      
```

- 英語の情報
```
- title: DOT for kiddies
- detail: DOT is the essence of Scala. It testifies that Scala is not a random set of features but a system. I’ll explain DOT to those without a background in the theory of PLs. Starting with an idea of a theory for PL, I’ll present DOT, show examples and explain what is proved about it. I’ll also link DOT to dotty.
```

- [ ] 和訳
- [ ] 日本語版の掲載

- 追加発表者の有無
```

```
  - [ ] Yesの場合には追加発表者を掲載する
