### ISSUE TITLE
[英語フォーム] CFPの和訳と掲載: Manuel Bernhardt さんによる「Those anti-patterns you’ll never see: how Akka 2.6 changes the way of building maintainable distributed systems」

### ISSUE THREAD

**Issue by tomoco95** [scalamatsuri/2020.scalamatsuri.org#57]
```
id: "" # proposalは人名-No
ja:
  candidate:
    name: "Manuel Bernhardt"
    twitter: elmanu
    github: https://github.com/manuelbernhardt
    other_sns: https://www.linkedin.com/in/manuelbernhardt/
    icon: https://en.gravatar.com/userimage/18124135/34183f2109d6ec0eb54d349c10a4d2dc.png
    organization: manuel.bernhardt.io, Reactive & Distributed Systems Consultant
    contributes:
      - - https://github.com/manuelbernhardt/akka-locality
- https://github.com/lightbend/Pi-Akka-Cluster
    speaker_experience:
      - A full list of the talks I have given including links to recordings and slides is available here: https://manuel.bernhardt.io/talks/
  program:
    title: ""
    length: 40 minutes
    language: English
    tags:
      - Best Practices, Software Design and Architecture, Microservices
    keywords:
      - Akka Typed
Distributed Systems
Best practice
    detail: |
      
```

- 英語の情報
```
- title: Those anti-patterns you’ll never see: how Akka 2.6 changes the way of building maintainable distributed systems
- detail: Akka has been used for over a decade to build mission-critical systems, yet the Classic API also has its set of shortcomings. With the release of Akka 2.6, the majority of these anti-patterns have now been rendered impossible by design. This talk shows how to make best use of the new release.
```

- [ ] 和訳
- [ ] 日本語版の掲載

- 追加発表者の有無
```

```
  - [ ] Yesの場合には追加発表者を掲載する
