### ISSUE TITLE
追加発表者の掲載: 「(テストデータ)バックオフィスでScala使ってみた」

### ISSUE THREAD

**Issue by tomoco95** [scalamatsuri/2020.scalamatsuri.org#6]
```
  candidate:
    name: "いわじ えいみ"
    twitter: scala_jp
    github: Iwaji
    icon: https://twitter.com/scala_jp
    organization: ScalaMatsuri準備委員会
    contributes:
      - - backoffice
- scalamatsuri
    speaker_experience:
      - - ScalaMatsuri2017(test)
- ScalaMatsuri2018(test)
  program:
    title: "(テストデータ)バックオフィスでScala使ってみた"
```

- 英語の情報
```
- name: Eimi Iwaji
```

- [ ] 追加発表者の掲載
