### ISSUE TITLE
[英語フォーム] CFPの和訳と掲載: Marc Hauser Guinness World Record Holder さんによる「We do not need wings to fly」

### ISSUE THREAD

**Issue by tomoco95** [scalamatsuri/2020.scalamatsuri.org#62]
```
id: "" # proposalは人名-No
ja:
  candidate:
    name: "Marc Hauser Guinness World Record Holder"
    twitter: 
    github: 
    other_sns: 
    icon: https://image.jimcdn.com/app/cms/image/transf/none/path/sc22fcdabd724a723/image/if342e5bf6f54d20b/version/1429459844/speaker-motivational-keynote-speaker-speaker-on-the-topics-of-courage-and-motivation-marc-hauser.jpg
    organization: erfolgswelle® Ltd.
    contributes:
      - 
    speaker_experience:
      - https://www.erfolgswelle.ch/redner/redner-referenzen/
  program:
    title: ""
    length: 40 minutes
    language: English
    tags:
      - Others
    keywords:
      - Guinness World Record Holder
Fastest man on erath in horizontal free fall
First time jet stream skydiver
Ambassador for high-altitude wind-power

    detail: |
      
```

- 英語の情報
```
- title: We do not need wings to fly
- detail: https://www.erfolgswelle.ch/keynote-speaker-website-english/

Guinness World Record holder for the first skydive into the Jet Stream 2018
```

- [ ] 和訳
- [ ] 日本語版の掲載

- 追加発表者の有無
```

```
  - [ ] Yesの場合には追加発表者を掲載する
