### ISSUE TITLE
[英語フォーム] CFPの掲載: Yumi Shibazaki(display name)さんによる「(test)Enjoy Scala at backoffice」

### ISSUE THREAD

**Issue by tomoco95** [scalamatsuri/2020.scalamatsuri.org#8]
```
id: "" # proposalは人名-No
en:
  candidate:
    name: Yumi Shibazaki(display name)
    twitter: scala_jp
    github: YumiShibazaki
    icon: https://twitter.com/scala_jp
    organization: JSA backoffice team
    contributes:
      - - OSS test1
- OSS test2
- OSS test3
    speaker_experience:
      - - ScalaMatsuri2019
  program:
    title: "(test)Enjoy Scala at backoffice"
    length: 100 minutes (contains 20 minutes' break in all)
    language: English
    tags:
      - Functional Programming, Best Practices, DevOps
    suggestions:
      - Keywords1
Keywords2
Keywords3
    detail: |
      (実際には英語の概要が入ります)テストなので好き勝手に書いてしまいました。すみません。
```

- [ ] 英語版の掲載

- 追加発表者の有無
```
（要レビュー）No. There is no presenter but me.
```
- [ ] Yesの場合には追加発表者を掲載する
