### ISSUE TITLE
[英語フォーム] CFPの掲載: Jeremy Smithさんによる「3 Approaches for Differential Programming in Scala 3」

### ISSUE THREAD

**Issue by tomoco95** [scalamatsuri/2020.scalamatsuri.org#87]
```
id: "" # proposalは人名-No
en:
  candidate:
    name: Jeremy Smith
    twitter: jeremyrsmith
    github: jeremyrsmith
    other_sns: LinkedIn – gentleman-and-a-scala
    icon: https://media.licdn.com/dms/image/C5103AQGks89-_T34jA/profile-displayphoto-shrink_200_200/0?e=1579737600&v=beta&t=Y82SwWQacla9J-7SEPXsRe9E_lhZGa7wJZEKdQ4rw_w
    organization: Senior Software Engineer at Netflix
    contributes:
      - Creator of Polynote – github.com/polynote/polynote
Creator of circe-yaml – github.com/circe/circe-yaml
Occasional contributor to shapeless

    speaker_experience:
      - Scala eXchange 2018 – no video, but slides are here: https://jeremyrsmith.github.io/scalax-workshop/
ScalaDays 2019 – Video is here: https://www.youtube.com/watch?v=BfaBeT0pRe0 and slides are here: https://jeremyrsmith.github.io/baudrillard/slides/
Scale by the Bay 2019 – Video is here: https://www.youtube.com/watch?v=QplRowWRNuQ (slides aren't yet posted)
  program:
    title: "3 Approaches for Differential Programming in Scala 3"
    length: 40 minutes
    language: English
    tags:
      - Functional Programming, Data Science / Machine Learning
    keywords:
      - differentiable programming
machine learning
dotty
    detail: |
      This talk will introduce and motivate automatic differentiation, and will describe some different approaches to AD in Scala 3 – including dual numbers (forward AD), type-oriented symbolic differentiation, and reverse AD with TASTy reflection.
```

- [ ] 英語版の掲載

- 追加発表者の有無
```

```
- [ ] Yesの場合には追加発表者を掲載する
