### ISSUE TITLE
[英語フォーム] CFPの掲載: Pierangelo Cecchettoさんによる「Ray Tracing with Environmental Effects」

### ISSUE THREAD

**Issue by tomoco95** [scalamatsuri/2020.scalamatsuri.org#99]
```
id: "" # proposalは人名-No
en:
  candidate:
    name: Pierangelo Cecchetto
    twitter: https://twitter.com/pierangelocecc
    github: https://github.com/pierangeloc/
    other_sns: 
    icon: https://twitter.com/pierangelocecc/photo
    organization: TulipLogic B.V.
    contributes:
      - I contribute mainly to zio projects. zio, zio-kafka, zio-macros
    speaker_experience:
      - I gave talks at local meetups in Amsterdam, and I gave a talk at BeeScala 2019. Video recording will be available soon (I can provide them as soon as available). For the slides see https://www.slideshare.net/PierangeloCecchetto/environmental-effects-a-ray-tracing-exercise-197041442
  program:
    title: "Ray Tracing with Environmental Effects"
    length: 40 minutes
    language: English
    tags:
      - Functional Programming, Best Practices, Software Design and Architecture
    keywords:
      - zio, architecture, ray-tracing
    detail: |
      In this talk I will introduce you to environmental effects as provided by ZIO. We will use them to build a fully working ray tracing application, discovering the basics of ray tracing and finding out how  environmental effects allow us to build functional, modular, fully testable applications. All this with full type inference and without the need of deep knowledge of the Scala type system.
```

- [ ] 英語版の掲載

- 追加発表者の有無
```

```
- [ ] Yesの場合には追加発表者を掲載する
